[feature] 마커 클릭 시 인포윈도우 표시 및 인포윈도우 클릭 시 상세 정보 화면으로 이동
boostcampwm-2024/and06-musicroad pull request #101
Opened 2024-11-14 07:11 UTC by meanjoo

## #️⃣연관된 이슈
- resolved #40 
- resolved #46 

## 📝작업 내용 및 코드
- 작업 내용 요약
  - 마커 클릭 시 해당 마커가 커지며 인포윈도우가 표시됨
  - 인포윈도우를 클릭하면 상세 정보 화면으로 이동
 
### 마커 클릭 테스트
마커 클릭을 테스트해보기 위해 임의의 마커를 생성하고 클릭했을 때 클릭한 마커만 크기가 커지도록 하는 작업을 했습니다.
아이콘의 크기는 width와 height 속성을 지정하여 변경할 수 있습니다. 클릭했을 때 클릭된 마커의 크기를 키우기 위해서는 아래처럼 클릭 리스너를 달고 클릭 이벤트로 초기 크기의 n배로 키우면 됩니다. 저는 1.5배로 키웠습니다.
```kotlin
marker.setOnClickListener {
    marker.width = (markerIconView.measuredWidth * MARKER_SCALE).toInt()
    marker.height = (markerIconView.measuredHeight * MARKER_SCALE).toInt()

    true
}

private const val MARKER_SCALE = 1.5
```

이렇게 모든 마커에 클릭 리스너를 달게 되면 클릭한 마커가 커집니다. 그런데 정말 클릭한 게 커지기만 합니다.

<img src="https://github.com/user-attachments/assets/2da55a1c-e7d4-4f45-9d7d-e3fff70a6fba" width="250">

클릭한 것만 커지고 이전에 클릭한 게 있다면 작아지게 하려 했습니다. 또한 마커가 클릭된 상태로 지도 위 빈 곳을 누르면 마커 선택을 해제(=크기 원상 복구)하려 했습니다.

그러기 위해 선택된 마커를 관리하는 변수를 프래그먼트에 생성하고, 마커를 생성할 때 마커에 클릭 리스너를 설정했습니다.

선택된 마커를 다시 클릭하면 아무 동작도 일어나지 않게 합니다. 현재 클릭한 마커 이전에 선택된 마커가 있으면 해당 마커의 크기는 기본 크기로 바꿉니다. 클릭한 마커는 기본 크기의 1.5배로 크기를 키우고 선택된 마커로 설정합니다.

```kotlin
private var selectedMarker: Marker? = null

private fun createMarker(location: Location) {
    val marker = Marker()
    val markerIconView = MarkerIconView(requireContext())
    markerIconView.setPaintColor(Blue.toArgb())
    markerIconView.loadImage("https://i.scdn.co/image/ab67616d0000b2733d98a0ae7c78a3a9babaf8af") {
        marker.position = LatLng(location.latitude, location.longitude)
        marker.icon = OverlayImage.fromView(markerIconView)
        marker.setOnClickListener {
            onMarkerClick(marker)
            true
        }
        marker.map = naverMap
    }
}

private fun onMarkerClick(marker: Marker) {
    if (selectedMarker == marker) return // 선택된 마커를 다시 클릭하는 경우 -> 아무 동작도 하지 않도록

    val defaultIconWidth = marker.icon.getIntrinsicWidth(requireContext())
    val defaultIconHeight = marker.icon.getIntrinsicHeight(requireContext())

    // 선택된 마커가 있는 경우
    selectedMarker?.let {
        it.width = defaultIconWidth
        it.height = defaultIconHeight
    }

    marker.width = (defaultIconWidth * MARKER_SCALE).toInt()
    marker.height = (defaultIconHeight * MARKER_SCALE).toInt()
    selectedMarker = marker
}
```

지도의 클릭 이벤트는 `naverMap.setOnMapClickListener`로 설정할 수 있습니다. pointF는 누른 위치의 화면 상 좌표, latLng는 누른 위치의 위도, 경도입니다. naverMap 객체가 준비되면 호출되는 `onMapReady()`에서 설정하는 것이 적합하다고 생각했습니다.
```kotlin
naverMap.setOnMapClickListener { pointF, latLng ->
		/* TODO */
}
```

지도 위를 클릭했을 때 선택된 마커가 있으면 해당 마커의 선택을 해제합니다.

```kotlin
override fun onMapReady(naverMap: NaverMap) {
		/* ... */
		
    // 지도 클릭 이벤트 설정
    naverMap.setOnMapClickListener { _, _ ->
        selectedMarker?.let { marker ->
            marker.width = marker.icon.getIntrinsicWidth(requireContext())
            marker.height = marker.icon.getIntrinsicHeight(requireContext())
            
            selectedMarker = null
        }
    }
    
		/* ... */
}
```

이렇게 마커와 지도에 클릭 리스너를 설정하면 아래와 같이 원했던 대로 됩니다.

<img src="https://github.com/user-attachments/assets/deecf4ef-6771-4add-bf59-6351636daa91" width="250">

- **마커의 onClick()이 false를 반환하는 이유**
마커의 onClick()이 false를 반환하면 이벤트가 소비되지 않고 전파되므로 지도의 onClick()도 호출됩니다. 마커의 onClick()에서는 클릭한 마커를 선택된 마커로 설정하고 크기를 키우고 있고, 지도의 onClick()에서 선택된 마커가 있으면 크기를 원래 크기로 만들고 있습니다. 이벤트가 전파된다면 마커의 onClick()이 호출된 후 지도의 onClick()도 호출되기 때문에 마커를 클릭해도 크기가 커지지 않습니다.
마커의 onClick()에서 true를 반환하면 이벤트가 소비되므로 지도의 onClick()은 호출되지 않습니다.

### 파이어베이스 정보로 마커와 인포윈도우 표시하기
마커 클릭 테스트를 한 이후에는 현재 위치를 기준으로 반경 안에 있는 파이어베이스에 있는 픽 정보를 불러온 후 이 픽 정보를 가지고 지도에 마커를 표시한 후 클릭 이벤트를 설정했습니다. 마커를 클릭하면 해당 마커가 나타내는 픽의 정보를 인포윈도우에 보여줘야 합니다.

현재는 네이버커넥트 기준 주변 5km 내의 픽 정보를 불러와서 보여주고 있습니다.

다음 과정을 통해 파이어베이스의 정보로 마커와 인포윈도우를 나타낼 수 있도록 했습니다. 뷰모델에서 픽 정보 리스트, 선택된 픽을 관리합니다. 맵 프래그먼트에서는 픽 정보 리스트를, 맵 스크린에서는 선택된 픽을 구독하고 있습니다. 맵 프래그먼트에서 픽 정보 리스트를 가지고 마커를 그리고 마커가 클릭되면 마커가 나타내는 픽을 뷰모델의 선택된 픽으로 설정합니다. 맵 스크린에서 선택된 픽에 따라 인포윈도우를 설정합니다.

MapViewModel에서 픽 정보를 가져오면 이를 가지고 마커를 생성하기 위해 뷰모델에 픽 정보 리스트를 관리하는 StateFlow를 만듭니다. MapFragment에서는 StateFlow를 구독하고 여기서 픽 리스트를 가지고 마커를 생성합니다. 픽 정보를 가져오는 것은 뷰모델에 구현되어 있던 `fetchPickInArea()`에서 정보 불러오기에 성공했으면 픽 정보 리스트를 업데이트해주기만 했습니다. 추가로 선택된 픽을 관리하는 변수도 만들고 이를 업데이트하는 함수도 만들어줍니다.

```kotlin
@HiltViewModel
class MapViewModel @Inject constructor(
    private val fetchPickInAreaUseCase: FetchPickInAreaUseCase
) : ViewModel() {
		private val _pickList = MutableStateFlow<List<Pick>>(emptyList())
    val pickList = _pickList.asStateFlow()
    
    private val _selectedPick = MutableStateFlow<Pick?>(null)
    val selectedPick = _selectedPick.asStateFlow()
    
    fun fetchPickInArea(lat: Double, lng: Double, radiusInM: Double) {
        viewModelScope.launch {
            val picks = fetchPickInAreaUseCase(lat, lng, radiusInM)

            picks.onSuccess {
                _pickList.value = it
            }
            picks.onFailure {
                // TODO
            }
        }
    }
    
    fun setSelectedPick(pick: Pick) {
        viewModelScope.launch {
            _selectedPick.value = pick
        }
    }

    fun resetSelectedPick() {
        viewModelScope.launch {
            _selectedPick.value = null
        }
    }
}
```

`onMapReady()`에서 픽 정보 리스트를 구독하고 여기서 마커를 만들어줍니다. 픽 정보 리스트가 변할 때마다 마커를 다시 그리는데 아직 캐싱이나 최적화하는 방법까지는 생각하지 못했고, 일단은 기존에 있던 모든 마커를 지우고 새로 마커를 생성하는 방식으로 구현해두었습니다.

맵 프래그먼트에 지도의 마커 리스트를 관리하는 변수를 둡니다. 픽 정보 리스트를 가지고 지도에 마커를 생성하기 전에 기존에 마커가 있다면 이를 전부 삭제합니다. 마커를 생성하는 것은 기존에 마커를 생성하는 것과 똑같은데 마커의 아이콘에 들어가는 이미지, 마커의 위치만 픽 정보 리스트의 값으로 바꿔주면 됩니다.

클릭 이벤트도 마커를 클릭했을 때 뷰모델에 있는 선택된 픽을 해당 마커가 나타내는 픽으로 변경하기 위해 기존 함수에 pick만 추가된 것뿐입니다. 또한 지도를 클릭했을 때 선택된 마커가 있으면 이를 선택해제 하는 곳에서 뷰모델의 선택된 픽도 해제되도록 합니다.

```kotlin
class MapFragment : Fragment(), OnMapReadyCallback {
		private val markers = mutableListOf<Marker>()
		
		override fun onMapReady(naverMap: NaverMap) {
				naverMap.setOnMapClickListener { _, _ ->
            selectedMarker?.let { marker ->
                /* ... */
                mapViewModel.resetSelectedPick()
            }
        }
        
        lifecycleScope.launch {
            mapViewModel.pickList.collect {
                createMarker(it)
            }
        }
    }
    
    private fun createMarker(pickList: List<Pick>) {
        // 기존 마커 삭제
        markers.forEach { it.map = null }
        markers.clear()

        pickList.forEach { pick ->
            val marker = Marker()
            val markerIconView = MarkerIconView(requireContext())
            markerIconView.setPaintColor(Blue.toArgb())
            markerIconView.loadImage(pick.song.getImageUrlWithSize(RequestImageSize)) {
                marker.position = LatLng(pick.location.latitude, pick.location.longitude)
                marker.icon = OverlayImage.fromView(markerIconView)
                marker.setOnClickListener {
                    onMarkerClick(marker, pick)
                    true
                }
                marker.map = naverMap
            }
        }
    }
    
    private fun onMarkerClick(marker: Marker, pick: Pick) {
        /* ... */
        mapViewModel.setSelectedPick(pick)
    }
}
```

선택된 픽이 있을 때 보여지는 인포윈도우는 MapScreen에서 관리해야하기 때문에 MapScreen에서 뷰모델의 선택된 픽을 구독합니다. 선택된 픽이 null이면 선택된 것이 없다는 뜻이므로 인포윈도우를 보여주지 않고, null이 아니라면 해당 픽의 정보를 가지고 인포윈도우를 보여주면 됩니다.

### 인포윈도우를 클릭하면 해당 픽 상세 정보 화면으로 이동
MapScreen에서 인포윈도우를 클릭하면 해당 픽 상세 정보 화면으로 이동해야 합니다. 픽 상세 정보 화면으로 이동할 때는 해당 화면에서 보여줄 픽의 id를 함께 넘겨야 합니다.

MapScreen에 인포윈도우를 클릭했을 때 수행할 동작을 추가해주고 내비게이션도 추가합니다.

목적지(픽 상세 정보 화면)로 갈 때 값을 전달하기 위해 composable에 route와 arguments를 설정합니다. arguments는 route를 통해 전달받은 값들의 리스트입니다.

```kotlin
@Composable
fun MainNavGraph(
    mapViewModel: MapViewModel,
    navController: NavHostController,
    navigationActions: MainNavigationActions,
    modifier: Modifier = Modifier,
    startDestination: String = MainDestinations.MAIN_ROUTE,
) {
    NavHost(
        navController = navController,
        startDestination = startDestination,
        modifier = modifier
    ) {
        composable(MainDestinations.MAIN_ROUTE) {
            MapScreen(
                /* ... */
          [...]

2024-11-14 08:21 UTC, yuni-ju reviewed
추후 Pick 데이터 클래스에서 userId가 아닌 닉네임도 추가해야겠네요 ㅎㅎ

2024-11-14 08:31 UTC, yuni-ju approved these changes
마커 클릭 부터 화면 줌, 인포윈도우 표시, 픽 상세화면으로 이동까지!!! 넘 고생하셨습니다 👍

2024-11-14 08:35 UTC, meanjoo commented
> 인포윈도우 `text = pick.createdBy` 부분 추후 Pick 데이터 클래스에서 userId가 아닌 닉네임도 추가해야겠네요 ㅎㅎ

앗 그러네용 닉네임이 id 값 그대로 나오고 있네요 ㅋㅋㅋ 좋습니다!

2024-11-14 16:05 UTC, miller198 requested changes

2024-11-14 16:05 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/NaverMapFragment.kt
> +    private val markers = mutableListOf<Marker>() // 지도의 마커 리스트
선택된 마커나, 현재 지도의 마커 리스트 모두 뷰의 상태에 해당하는데 뷰모델을 사용함에도 불구하고 Fragment에서 이를 저장하고 있으면 안되지 않을까요? 뷰모델 사용의미에 많이 어긋나는것 같아요
동일한 내용으로 학습스프린트 간 멘토님께 지적받은게 기억나네요

2024-11-14 16:05 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +        }
DetailPick에선 MapViewModel에 접근이 가능하므로 뷰모델을 통해 현재 MapViewModel에 있는 selectedPick을 받아오는게 좋아보입니다.
검색 -> 등록 -> 디테일 에선 DetailPickScreen 파라미터로 콜백 넣어주면 MapViewModel의 setSelectedPick() 같은 함수에 접근이 가능할것같은데 어떻게 생각하세요

2024-11-14 16:11 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +        }
아 빼먹었는데 DetailPickScreen에서 PickViewModel가 필요없을 것이다 라는 의견도 포함입니다

2024-11-14 16:13 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +        }
DetailPickScreen에서 setSelectedPick() 함수에 접근해야 할 일이 있나요??

2024-11-14 16:21 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +        }
DetailPickScreen -> CreatePickScreen 입니다 죄송스 ㅎ

2024-11-19 02:25 UTC, yuni-ju requested changes

2024-11-19 02:25 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +    val pickMap = _pickMap.asStateFlow()
pickMap이 지도의 Map인지 자료구조의 Map인지 헷갈리는 것 같습니다. 
그리고 변수명에 자료 구조를 직접 나타내는 것보다 의미가 더 드러나게 지정하는 것은 어떨까 싶습니다.

지금 떠오르는 것으로... `pickMarkers`가 어떤지 제안드립니다!

2024-11-19 02:25 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +
아래의 코드를 보았을 때 `selectedPick`과 `selectedMarker`가 항상 동시에 지정되는 것 같은데 실수 방지를 위해 Pair 등으로 묶어서 관리하는 것은 어떤가요?

2024-11-19 02:25 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +                }
```kotlin
it.forEach { pick ->
    newMap[pick] = _pickMap.value[pick] ?: Marker()
}
```

좀 더 간결하게 작성할 수 있을 것 같습니다

2024-11-19 02:25 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +    fun setMapToMarker(map: NaverMap) {
현재 우리의 코드는 ViewModel에서 화면의 상태만을 갖고있고, UI는 상태의 변경에 따라 업데이트하는 역할을 하고 있습니다.  

해당 목표에 따라 지도 객체를 ViewModel로 전달하는 것보다 UI가 마커의 상태 변경을 관찰해서 업데이트하는 것이 좋을 것 같습니다.

2024-11-19 02:25 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +                        selectedMarker = mapViewModel.selectedMarker,
selectedMarker StateFlow 자체를 하위 컴포넌트로 계속 전달하는 방법 이외에
selectedMarker의 상태 변경을 관찰해서 이에 따라 관련 UI가 바뀌도록 로직을 바꿔보는 것은 어떨까요? 

pickMap은 collectAsStateWithLifecycle()를 사용했는데, selectedMarker는 이를 사용하지 않은 이유가 궁금합니다!

2024-11-19 02:37 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +    val pickMap = _pickMap.asStateFlow()
좋습니다! 저도 다시 보니 그렇네요
변수명 변경하도록 하겠습니다 🙌

2024-11-19 03:04 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +                        selectedMarker = mapViewModel.selectedMarker,
selectedMarker의 상태 변경 관찰로 얻을 수 있는 게 없다고 생각하여 collectAsStateWithLifecycle()을 사용하지 않았었습니다.
당연히 selectedMarker의 상태 변경 관찰을 하면 클릭된 마커의 크기를 키울 수 있을 것입니다. 그런데 현재 클릭한 마커 이전에 클릭했던 마커가 있다면 이전 마커의 크기는 작아져야 하는데 이전에 클릭된 마커를 알 수 있는 방법이 없다고 생각하여 저렇게 StateFlow를 넘겼었습니다.
클릭 이벤트에 StateFlow 자체를 넘김으로써 가장 최근에 클릭된 마커를 알 수 있도록 하기 위함이었습니다. StateFlow의 값과 현재 클릭된 마커를 비교하여 이전에 클릭된 마커가 무엇인지 알 수 있었습니다.

그런데 저도 StateFlow 자체를 넘기는 게 맞을까 라는 생각을 계속 하긴 했었습니다..
클릭 이벤트에 StateFlow를 넘기지 않고 selectedMarker를 관찰하면서 UI가 변경되도록 로직을 한번 변경해보겠습니다!

2024-11-19 03:07 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +    selectedMarker: StateFlow<Marker?>,
selectedMarker를 StateFlow 타입으로 받아서 쓰는 이유가 있나요?

2024-11-19 03:08 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +    selectedMarker: StateFlow<Marker?>,
앗 위에 똑같은 리뷰가...위에 달아주신 답변 참고하겠습니다

2024-11-19 03:09 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +    selectedMarker: StateFlow<Marker?>,
클릭이벤트 설정은 한 번만 이루어지는데 StateFlow가 아닌 Marker로 받으면 클릭이벤트를 설정할 때의 Marker가 selectedMarker가 되어 가장 최근에 선택된 마커가 아니게 되어서 StateFlow로 받아서 사용했습니다.

2024-11-19 03:14 UTC, miller198 reviewed
_pickMarkers를 새로 설정할때 이전에 있던 마커지만 새로 불러온 _pickMarkers 에선 없는 마커는 삭제가 안되고 있는 거죠?

2024-11-19 03:41 UTC, meanjoo commented
> _pickMarkers를 새로 설정할때 이전에 있던 마커지만 새로 불러온 _pickMarkers 에선 없는 마커는 삭제가 안되고 있는 거죠?

새로운 픽 리스트로 맵을 만들고 바꾸면서 새로 불러온 거에 없는 마커는 삭제가 되고 있습니다.
```kotlin
picks.onSuccess {
    val newMap = mutableMapOf<Pick, Marker>()
    it.forEach { pick ->
        newMap[pick] = _pickMarkers.value[pick] ?: Marker()
    }
    _pickMarkers.value = newMap
}
```

2024-11-19 08:07 UTC, yuni-ju approved these changes
엇 몰랐는데 commit description에 co-authored가 텍스트로 있었네용 ㅋㅋㅋ (무시하셔도 됩니다!!!) 
픽 상태 관찰해서 토글로 변경하는 코드 좋은 것 같아요 !! 넘 고생하셨습니다 👍 👍 👍 🤩

2024-11-19 08:25 UTC, meanjoo commented
@yuni-ju 
같이 논의하고 했던 거라 co-author 적용하려고 했는데 뭔갈 잘못했나봐요 ㅠㅠ.. 다음 번엔 더 신경쓰겠습니다 ㅠㅠㅠ
그리고 토글 부분은 제가 한 게 아닙니다 ㅎㅎ 승규님에게 박수를 👏👏

2024-11-19 08:33 UTC, miller198 approved these changes

2024-11-19 08:39 UTC, merged