[feature] MapFragment 제거 후 MapScreen에서 지도 기능 통합
boostcampwm-2024/and06-musicroad pull request #106
Opened 2024-11-17 14:11 UTC by yuni-ju

## #️⃣연관된 이슈

> - resolved #105 

## 📝작업 내용 및 코드

- MapFragment를 제거하고 MapScreen에서 지도 기능을 사용할 수 있도록 했습니다.
- [구현 과정 및 결과 문서](https://cultured-lan-6c6.notion.site/NaverMap-Composable-141ea5e5fc178062af40c1452017b50e?pvs=4)

2024-11-17 15:57 UTC, meanjoo requested changes
MapScreen 안에 모든 코드를 넣었는데 네이버 지도 부분만 NaverMapScreen으로 분리하는 건 어떤가요??
지도 부분 코드가 많을 것 같아 분리하는 게 나중에 더 보기 편할 것 같은데 이건 정말 개인적인 의견입니다 ㅎㅎ 고생하셨습니다!

2024-11-17 15:57 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +private const val TAG_LOG = "MapFragment"
MapFragment를 없애면서 미처 없어지지 않은 부분 같습니닷 ㅎㅎ

2024-11-17 15:57 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                    naverMap.value = map
위에 보면 `val naverMap = remember { mutableStateOf<NaverMap?>(null) }`로 선언했는데 혹시 이 부분에 아래처럼 사용하시려던 걸까요?
```kotlin
if (naverMap.value == null) {
    mapView.getMapAsync { map ->
        naverMap.value = map
}
```
![image](https://github.com/user-attachments/assets/4a7498fd-7077-48fe-a4d5-a96f206fdfc3)

update가 리컴포지션이 일어날 때마다 호출되는 곳으로 알고 있는데 현재 코드대로면 NaverMap 객체를 리컴포지션이 일어날 때마다 새로 만들게 되지 않을까요?
제가 잘못 이해하고 있는 거라면 알려주시면 감사하겠습니다..!

2024-11-17 15:57 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +    uiSettings.isTiltGesturesEnabled = false
요 부분은 따로 빼면 어떨까요?!
개인적인 생각이지만 이 세 줄은 LocationOverlay보다는 지도 세팅 부분 같아서 함수 이름에 안 어울린다는 느낌이 들어서요..!

아래처럼 지도를 세팅하는 걸 하나로 만들어서 그 안에 최대/최소 줌 레벨 설정이랑 uiSetting을 넣어도 좋을 것 같아요.

```kotlin
private fun NaverMap.initMapSettings() {
    setCameraZoomLimit()
    uiSettings.defaultSetting()
}

// setCameraZoomLimit() 함수

private fun UiSettings.defaultSetting() {
    isLocationButtonEnabled = true
    isZoomControlEnabled = false
    isTiltGesturesEnabled = false
}
```
만약 이렇게 한다면 getMapAsync 안의 setCameraZoomLimit()을 initMapSettings()로 변경하면 될 것 같습니다!

2024-11-17 15:57 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +    val mapView = remember { MapView(context) }
mapView의 lifecycle은 따로 관리하지 않아도 되는 괜찮은 건가요?
제가 참고했던 자료들은 전부 mapView의 lifecycle을 직접 관리하고 있던데 그런 코드가 안 보여서 여쭤봅니다..!!

[배달의민족에 Jetpack Compose 적용을 시도해보았다](https://www.youtube.com/watch?v=BX0rQvYgf1I) <- 이 영상의 지도 화면 전환 부분
[NAVER-MAP-COMPOSE](https://github.dev/fornewid/naver-map-compose/blob/main/app/src/main/java/com/naver/maps/map/compose/demo/basic/MapScreen.kt)

2024-11-17 16:42 UTC, yuni-ju commented
@meanjoo 
지도 screen 분리하는 것 넘 좋은 것 같습니다!! 👍 
PR 제목 태그는 저희 컨벤션을 참고해서 지정했습니닷 ㅎㅎ

2024-11-17 16:43 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                    naverMap.value = map
어랏 그러네요..!  저 객체는 외부에서 네이버맵 객체를 쓸 일이 있을 경우를 위해 만들어 뒀었습니다. 수정하겠습니다!

2024-11-17 16:45 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +    uiSettings.isTiltGesturesEnabled = false
오 함수명 추천까지! 좋습니다!! 😄

2024-11-17 16:50 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +    val mapView = remember { MapView(context) }
이런 자료가 있는줄 몰랐네요..! 참고 자료와 함께 꼼꼼히 리뷰해 주셔서 감사합니다. 😊 민주님 최고

NAVER Map Compose 라이브러리를 참고해서 코드에 도입하겠습니다 🙌

2024-11-18 08:26 UTC, meanjoo approved these changes
👍👍

2024-11-18 08:50 UTC, miller198 approved these changes
고생하셨어요! 큰 버그 하나 드디어 해결 ╰(*°▽°*)╯

2024-11-18 08:50 UTC, merged