[feature] 현재 위치 저장 및 공유 위한 데이터 레이어 구현
boostcampwm-2024/and06-musicroad pull request #109
Opened 2024-11-18 15:14 UTC by miller198

## #️⃣연관된 이슈

> closes #108

## 📝작업 내용 및 코드

1. LocalDataSource
```kotlin
class LocalDataSourceImpl : LocalDataSource {
    
    private var _userId: String? = null
    private var _currentLocation: MutableStateFlow<Location?> = MutableStateFlow(null)

    override val userId: String?
        get() = _userId

    override val currentLocation: StateFlow<Location?>
        get() = _currentLocation

    override fun saveUserId(userId: String) {
        _userId = userId
    }

    override suspend fun saveCurrentLocation(location: Location) {
        _currentLocation.emit(location)
    }
}
```
2. LocalRepository
```kotlin
class LocalRepositoryImpl @Inject constructor(
    private val localDataSource: LocalDataSource
) : LocalRepository {

    override val userId get() = localDataSource.userId
    override val currentLocation get() = localDataSource.currentLocation

    override suspend fun saveUserId(userId: String) {
        localDataSource.saveUserId(userId)
    }

    override suspend fun saveCurrentLocation(location: Location) {
        localDataSource.saveCurrentLocation(location)
    }
}
```
3. MapViewModel에서 5m 이상 이동해야 LocalDataSource의 현재 위치 값 변경하고 주변 픽 fetch 해오도록 

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-11-19 02:25 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
> +    }
검색 화면에서 현재 위치 값을 collect하는 이유가 있나요??

단지 값을 확인해보기 위해서 작성한 거라면 없어도 되지 않을까요? 현재 위치 값을 collect 하여 수행하는 작업이 있다면 어떤 것인지 궁금합니다.

2024-11-19 02:25 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +                saveCurLocation(location)
위치가 5m 변할 때마다 현재 위치를 저장하고 현재 위치가 변할 때 주변 픽을 불러오는 것은 좋은 것 같습니다!

등록할 때도 현재 위치 값을 쓰게 될 텐데 하나 궁금증이 있습니다.
현재 위치 값을 5m가 변할 때마다 저장한다면 그림처럼 초록색 사람이 왼쪽으로 이동하고 있을 때, 빨간색 점에서 위치 업데이트가 일어났으면 초록색 점에서 위치 업데이트가 다시 일어날 것입니다. 픽을 등록할 때 현재 위치 값을 사용할 텐데 그럼 사용자가 주황색 점에서 음악 등록 버튼 클릭을 누르면 빨간색 점에 마커가 생기게 되나요?
![image](https://github.com/user-attachments/assets/09fa873b-db53-4988-ac30-a7ec3a9939cd)

2024-11-19 03:21 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/create/SearchMusicScreen.kt
> +    }
collect 해서 UI업데이트같은 동작은 하지 않습니다.
생각해보니 UI에서 이걸 알고 있을 필요도 없군요. 단순히 CreatePickViewModel에서 가지고 있기만 하면 되네요
CreatePickViewModel에서 curLocation을 데이터 레이어에서 가져올때 일반 Location 타입으로 저장만 하도록 수정하겠습니다

2024-11-19 06:27 UTC, yuni-ju requested changes

2024-11-19 06:27 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
> +    private val fetchLocationUseCase: FetchLocationUseCase,
단순히 내부에서 값을 그대로 사용하려면 private val을 제거하고 fetchLocationUseCase: FetchLocationUseCase로 써도 될 것 같습니다

2024-11-19 06:27 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
> -    pickId: String,
제 개인적 의견으로는 DetailPick화면은 여러 경로로 편리하게 접근하고 재사용이 용이하도록 pickId를 파라미터로 전달 받아서 쓰는 것은 어떤가요? viewModel 내부에서 savedStateHandle로 전달받아 사용하는 것은 확인했으나 detail/pickId의 경로로 id값만 받아오는 것이 더 직관적일 것 같아보입니다! 

savedStateHandle로 전달 받도록 하신 이유가 궁금합니다.

2024-11-19 12:28 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
> -    pickId: String,
saveStateHandle로 전해진 데이터를 받아올 수 있는지 확인하다 남겨진 코드입니다 
수정해서 반영하겠습니다!

2024-11-19 12:29 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/create/CreatePickViewModel.kt
> +    private val fetchLocationUseCase: FetchLocationUseCase,
맞습니다 반영하겠습니다

2024-11-19 14:53 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                    },
지도에서 위치를 불러오기 전 버튼을 클릭하면 현재 위치가 null일 것입니다.
mapViewModel.onCenterButtonClick() 내부에서 null인 경우 값을 업데이트하지 않고, return을 한다고해도 등록 화면으로 넘어가는 상태인 것 같습니다! default 위치로 등록이 되긴하지만, 결국 사용자가 확인할 수 없는 위치라 의미가 없을 것 같다는 생각이 듭니다. 

혹시 현재 위치가 null이 아닐 때만 onCenterClick 내부의 기능이 동작하도록 하는 것은 어떨까요?

2024-11-19 15:00 UTC, yuni-ju reviewed
PickState에서 previous, current가 가리키는 픽이 없는 상태나 Location이 null일 때는 이를 명확하게 파악할 수 있도록 비어있는 문자열이나 0.0 값보다 nullable하게 쓰는 것은 어떨까요? 

DEFAULT_LOCATION을 썼을 때 그냥 null을 썼을 때보다 해당 값이 의미있게 쓰이거나 좀 더 장점이 있는지 궁금합니다!

2024-11-20 03:06 UTC, meanjoo requested changes

2024-11-20 03:06 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        val location = Location("").apply {
큰 의미가 있는 건 아니지만 Location의 provider로 `Location("pickLocation")`과 같이 의미있는 이름을 붙여주는 건 어떨까요?

![image](https://github.com/user-attachments/assets/d921b9d0-3339-43e6-89a4-27e1249da8a4)

생성자에서 이 위치와 연관된 provider 이름을 인자로 받는다고 하여 생각해본 것이었습니다!

2024-11-20 03:06 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        from.distanceTo(to).toDouble()
이 함수는 뷰모델 안의 updateCurLocation 안에서만 사용되는 것 같아서 private으로 변경해도 될 것 같습니다.

개인적으로는 함수 안에서 어떤 함수 하나만을 호출하고 있는데 굳이 이걸 함수로 분리해야했을까? 하는 생각이 듭니다. 함수 분리를 하지 않은 코드도 충분히 어떤 동작을 하는지 명확하다고 생각하는데 함수로 따로 분리하신 이유가 궁금합니다.
```kotlin
// in updateCurLocation()

// 현재 코드
if (calculateDistance(to = location) > 5.0) {
    saveCurLocation(location)
}

// 함수 분리를 하지 않았을 때
if (curLocation.value.distanceTo(location) > 5.0) {
    saveCurLocation(location)
}
```

2024-11-20 03:06 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        return from.distanceTo(location).toDouble()
현재 이 함수를 호출하는 곳은 한 군데 밖에 없고 아래와 같이 호출하고 있습니다.
`mapViewModel.calculateDistance(lat = lat, lng = lng).toInt().toString()`

from을 안 넘기고 있어서 기본 값인 curLocation.value가 사용되고 있습니다. 거리 계산 함수는 현재 위치를 기준으로만 사용될 것 같은데 from을 없애고 `return curLocation.value.distanceTo(location).toDouble()`로 변경해도 되지 않을까요? from을 받으면서 거리 계산 함수를 사용하는 곳이 있을지 궁금합니다.

2024-11-20 03:40 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                    },
이러면 CreatePickViewModel 에서 LocalDataSource의 위치데이터 불러왔을때 null 일 경우가 없겠네요 좋습니다

2024-11-20 04:14 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        from.distanceTo(to).toDouble()
처음에 이 함수를 인포윈도우에서 거리계산할때도 쓰지않을까 해서 public상태인 분리된 함수로 만들었습니다

인포윈도우 거리 계산도 구현한 지금 상황에서 거리계산 함수가 인포윈도우에서 사용하는 것과 updateCurLocation() 안에서 사용하는것 두개가 있는데 이 두개를 하나로 통합하는게 낫겠네요

2024-11-20 04:28 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        val location = Location("").apply {
넵 좋습니다

2024-11-20 04:31 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        return from.distanceTo(location).toDouble()
코틀린 실수는 기본이 Double형이라 제가 그걸 선호합니다
from 파라미터는 이걸 사용하는 곳이 없어도 함수 자체가 더 유연하고 확장성 있도록 파라미터는 남겨두고 기본값을 사용하는게 좋다고 생각했습니다. 일반적으로 거리계산에는 두개의 좌표가 필요하니까요

2024-11-20 04:46 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        return from.distanceTo(location).toDouble()
아하 그냥 왜 Double로 반환하나 궁금한 거였습니다!

함수 자체를 유연하게 만들기 위해서 from 파라미터를 남겨두고 기본값을 두는 이유는 이해했습니다.
함수를 더 유연하게 만드는 것도 좋지만 만약 프로젝트 내에서 전혀 from을 사용할 일이 없고 항상 from이 현재 위치로 고정된다면 calculateDistanceFromCurLocation()와 같이 아예 함수명 자체를 변경해도 나쁘진 않을 것 같네욥!

2024-11-20 04:52 UTC, miller198 commented
## 리뷰 반영사항

**1. curLocation -> lastLocation 변경**
LocalDataSource에 저장되는 위치 변수는
5미터 이상 유저 위치가 변할때마다 저장되는 변수이고, 
이는 실시간 현재 위치가 아니므로 의미를 명확히 하기위해 변경하였습니다

**2. 바텀 내비게이션 파일 분리**
컴포저블 함수가 길어져서 파일을 분리하였습니다

**3. 바텀 내비게이션 중앙버튼 클릭 시 마지막 위치값이 없으면 화면 전환 되지 않도록 수정**
```kotlin
@Composable
fun MapScreen(
    mapViewModel: MapViewModel,
    onFavoriteClick: () -> Unit,
    onCenterClick: () -> Unit,
    onSettingClick: () -> Unit,
    onInfoWindowClick: (String) -> Unit
) {
    val pickCount by mapViewModel.pickCount.collectAsStateWithLifecycle()
    val pickMarkers by mapViewModel.pickMarkers.collectAsStateWithLifecycle()
    val selectedPickState by mapViewModel.selectedPickState.collectAsStateWithLifecycle()
    val lastLocation by mapViewModel.lastLocation.collectAsStateWithLifecycle()
```
MapScreen에서 mapViewModel 의 lastLocation 관찰

```kotlin
BottomNavigation(
    modifier = Modifier.padding(bottom = 16.dp),
    onFavoriteClick = onFavoriteClick,
    onCenterClick = {
        // 마지막으로 저장된 위치값이 없으면 화면전환 X
        if (lastLocation != null) {
            onCenterClick()
            mapViewModel.saveCurLocationForced()
        }
    },
    onSettingClick = onSettingClick
)
```
BottomNavigation의 중앙 버튼에 대해 
lastLocation 이 null 이면 ( = 아직 유저 위치 불러와 저장하지 못한 상태) 동작되지 않도록 변경

```kotlin
fun createPick(
        onSuccess: (String) -> Unit
    ) {
        _selectedSong?.let { song ->
            viewModelScope.launch {
                val musicVideoUrl = searchMusicVideoById(song.id)

                if (lastLocation == null) {
                    /* TODO: DEFAULT 인 경우 -> LocalDataSource 위치 데이터 못 불러옴 */
                    return@launch
                }
```
이렇게 한다면 위의 CreatePickViewModel::createPick() 에서 lastLocation null체크를 안해도 될 것 같은데 어떻게 생각하세요?

CreatePickViewModel은 바텀내비게이션 등록버튼을 눌렀을때 SearchMusicScreen으로 전환되면서 그 인스턴스가 생성되는데,
SearchMusicScreen으로의 전환은 LocalDataSource의 lastLocation != null 일 경우에만 전환되기때문에 CreatePickViewModel에서 lastLocation == null 일 경우가 없을 것 같습니다

2024-11-20 05:07 UTC, meanjoo commented
3에 대한 제 생각입니다. lastLocation이 null이 아닐 때만 화면이 전환되면 createPick에서 널 체크를 하지 않아도 될 것 같긴 합니다.
혹시 이런 것도 가능할까요? lastLocation이 null일 때는 바텀 내비게이션 바의 중앙 버튼의 클릭을 막고 색상을 회색 같이 아직 상호작용 할 수 없을 것 같은 색으로 변경하는 것도 가능한가요?

2024-11-20 05:36 UTC, miller198 commented
비상 비상
![image](https://github.com/user-attachments/assets/47a1b2a0-cf5e-4a43-9f37-f880406a0525)

바텀 버튼 위치가 이상해졌는데 도와주세요

2024-11-20 05:45 UTC, miller198 commented
@meanjoo 

[untitled.webm](https://github.com/user-attachments/assets/3012c516-be20-42de-92ec-eb0582dd1277)


이렇게 하면 될까요?

2024-11-20 05:50 UTC, meanjoo commented
@miller198 오!👍👍👍 저는 좋은데 윤겸님 의견도 들어봅시당

2024-11-20 05:59 UTC, yuni-ju commented
저도 좋은 것 같습니다! 👍

2024-11-20 06:01 UTC, yuni-ju approved these changes

2024-11-20 06:08 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        } ?: -1.0
이렇게 하면 인포윈도우에서 거리가 표시될 때 무조건 km 단위로 표시되더라구요.
저는 1km 이상일 때는 km 단위, 그 미만일 때는 m 단위로 나왔으면 좋겠는데 어떻게 생각하시나요??

만약 저렇게 하려면 calculateDistance()에서는 미터 단위로 반환하고 값을 사용하는 인포윈도우 쪽에서 체크하고 변환하는 건 어떤가요? 이렇게 한다면 코드는 이런 식으로 바꿀 수 있을 것 같아요.
```kotlin
// in MapViewModel.kt
fun calculateDistance(
    lat: Double,
    lng: Double,
    from: Location? = lastLocation.value,
): Double {
    return from?.let {
        val location = Location("pickLocation").apply {
            latitude = lat
            longitude = lng
        }

        from.distanceTo(location).toDouble()
    } ?: -1.0
}

// in MapScreen.kt
InfoWindow(
    pick,
    navigateToPick = { pickId ->
        onInfoWindowClick(pickId)
    },
    calculateDistance = { lat, lng ->
        val distance = mapViewModel.calculateDistance(lat = lat, lng = lng)
        when {
            distance >= 1000.0 -> String.format(Locale.getDefault(), "%.1fkm", distance / 1000.0)
            distance >= 0 -> String.format(Locale.getDefault(), "%.0fm", distance)
            else -> ""
        }
    }
)
```

2024-11-20 06:08 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +            || calculateDistance(location.latitude, location.longitude) > 5.0
calculateDistance()에 from을 안 넘겨서 기본 값인 lastLocation.value와 거리를 계산하고 있습니다. calculateDistance()에서 lastLocation.value가 null이면 -1을 반환해서 lastLocation.value가 널인 거를 체크할 필요가 없지 않을까요?
반환값이 > 5.0인지만 체크해도 될 것 같습니다.

2024-11-20 06:13 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +            || calculateDistance(location.latitude, location.longitude) > 5.0
그렇네요 반영하겠습니다!

2024-11-20 06:17 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +        } ?: -1.0
네 이 코드 사용해서 수정해볼게요

2024-11-20 06:23 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +            || calculateDistance(location.latitude, location.longitude) > 5.0
아하 그런가요 알겠습니당

2024-11-20 06:31 UTC, meanjoo approved these changes

2024-11-20 06:32 UTC, merged