[feature] 음원재생 UI, ExoPlayer 이용 음원재생 구현
boostcampwm-2024/and06-musicroad pull request #117
Opened 2024-11-21 15:51 UTC by miller198

## #️⃣연관된 이슈

resolve #102 
resolve #103

## 📝작업 내용 및 코드

ExoPlayer를 이용한 음원 재생 구현 및 플레이어 UI 디자인

[작업내용](https://cultured-lan-6c6.notion.site/ExoPlayer-145ea5e5fc1780849b36c0db2305b47e?pvs=4)

## 💬리뷰 요구사항(선택)

리컴포지션이 필요이상으로 자주 발생될것같은 부분이 있나 봐주세요

PlayerViewModel을 사용하는 컴포즈에서 hiltViewModel()로 호출한게 아니라 
NavHost에서 hiltViewModel로 생성하고 DetailPickScreen의 매개변수로 받은뒤 MusicPlayer 함수까지 전해주고 있는데
의도는 DetailPickScreen의 NavBackStackEntry에 PlayerViewModel이 계속 살아있도록 하려는 의도였습니다.
MusicPlayer에서 hiltViewModel() 로 생성해도 살아있는지는 잘 모르겠네요 더 알아볼게요

2024-11-22 02:56 UTC, yuni-ju requested changes
궁금한 것들 질문 남깁니다!

2024-11-22 02:56 UTC, yuni-ju commented on data/src/main/java/com/squirtles/data/di/FirebaseModule.kt
이 파일의 BuildConfig.FIRESTORE_DB_ID를 없애신 이유가 있을까요..!? 

만약 default DB를 쓰고싶으시다면 저 부분 코드를 그대로 두고,
`local.properties`파일에서 `FIRESTORE_DB_ID_DEBUG=(default)` 로 입력하시면 됩니닷

2024-11-22 02:56 UTC, yuni-ju commented on gradle/libs.versions.toml
> +
컨벤션에 따라 라인 하나 제거 부탁드립니다!

2024-11-22 02:56 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +private const val INITIAL_CAMERA_ZOOM = 16.0
이 부분 범위 바꾸게 된 이유가 궁금합니다!

2024-11-23 06:18 UTC, miller198 commented
@meanjoo @yuni-ju 
이거 괜찮으시면 수정할때 같이 반영하겠습니다
배너 한번 클릭하면 들리고 다시 누르면 노래 멈추고 이모지 바뀝니다

[untitled.webm](https://github.com/user-attachments/assets/510520d3-c8df-4937-bebe-b5ba75dafd88)

2024-11-23 07:01 UTC, yuni-ju commented
@miller198 지금 코드에 없는거죠? push해주시면 같이 확인하겠습니다!

2024-11-23 21:43 UTC, meanjoo requested changes
상단의 배너를 눌렀을 때 노래가 나오는 것 매우 좋습니다!👍👍👏
그런데 제 궁금증과 코멘트가 몇 개 있습니다.

1. 노래가 재생 중인 상태에서 configuration change가 일어나면 노래 재생이 취소되는데 의도한 걸까요?

2. 배너를 클릭할 때마다 노래가 재생/중지되는 것 같은데 어떨 때는 계속 노래가 바뀌고 어떨 때는 이전에 듣던 노래가 중지된 이후부터 다시 재생되는 것 같은데 제 기분 탓인가요??

3. 배너를 누르면 30초 미리듣기 음원이 랜덤으로 하나 재생되는데 30초 이후에는 다른 노래가 나오지 않고 배너가 아래처럼 된 상태로 그대로 유지되는 것 같습니다. 이 상태에서 배너를 누르면 이모지가 바뀌지도 않고 노래가 나오지도 않더라구요? 30초가 지나고 다른 노래가 다시 재생되는 게 아니라면 헤드셋 모양의 배너로 다시 바꿔주는 게 어떨까요 아니면 30초 재생이 끝나면 다른 노래를 랜덤으로 계속 재생해주는 것도 좋을 것 같아요!
![image](https://github.com/user-attachments/assets/c1d51d6e-dd20-450e-ba51-e76177e3e7d9)

4. 배너를 한 번 클릭할 때마다 리컴포지션이 두 번씩 일어나고 있는 것 같아요. 근데 이거 보니 배너 누를 때마다 NaverMap도 리컴포지션 두 번씩 일어나네요

https://github.com/user-attachments/assets/5849814f-e2ae-40a9-af07-2f97126aedda

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +            },
이 부분은 이렇게도 쓸 수 있을 것 같습니당

```kotlin
text = stringResource(
    id = if (isPlaying) R.string.map_pick_notification_stop else R.string.map_pick_notification_play,
    nearPicks.count()
),
```

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
>                  .padding(vertical = 10.dp, horizontal = 23.dp)
modifier 아래에 `color = Black` 넣어주실 수 있나요? 다크모드일 때 글자색이 이렇네용

![image](https://github.com/user-attachments/assets/f55b2863-a84b-4cbf-9b89-67273898327f)

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                Lifecycle.Event.ON_STOP -> playerViewModel.pause()
ON_PAUSE와 ON_STOP 둘 다 playerViewModel.pause()를 호출한다면 `Lifecycle.Event.ON_PAUSE, Lifecycle.Event.ON_STOP -> playerViewModel.pause()` 이렇게 쓸 수도 있습니다

그런데 ON_PAUSE와 ON_STOP 두 군데에서 전부 playerViewModel.pause()를 호출하는 이유가 있을까요?

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +        }
onDispose 안에서 `lifecycleOwner.lifecycle.removeObserver(lifecycleObserver)`를 해주는 게 어떨까요

[여기](https://developer.android.com/develop/ui/compose/side-effects?hl=en#disposableeffect)에서 코드에 주석으로 `When the effect leaves the Composition, remove the observer`라는 말이 있기도 하고, DisposableEffect에서 LifecycleEventObserver로 생명주기를 관리하는 것을 조금 더 편하게 해주는 LifecycleEventEffect가 있습니다. 이 안에서도 onDispose 안에서 옵저버를 제거해주고 있는 것을 보아 옵저버를 제거해주는 것이 좋을 것 같다고 생각했습니다.

![image](https://github.com/user-attachments/assets/39008e1d-ab9b-4178-a93d-35ace7f4b4e8)

2024-11-23 21:43 UTC, meanjoo commented on gradle/libs.versions.toml
> +androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
이걸 추가하면 어떤 아이콘들을 더 사용할 수 있는 건가요?

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/pick/musicplayer/MusicPlayer.kt
> +        }
MapScreen에서 removeObserver를 하시게 되면 여기도 부탁드립니다

2024-11-23 21:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/pick/musicplayer/PlayerViewModel.kt
> +private val INITIAL_PLAYER_STATE = PlayerState(isReady = false)
INITIAL_PLAYER_STATE를 따로 만드신 이유가 있을까요?

PlayerState 데이터 클래스의 isReady 기본 값을 false로 두고 `private val _playerState = MutableStateFlow(PlayerState())`로 만들어도 되지 않나? 라는 생각이 들어 여쭤봅니다!

2024-11-24 05:48 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +                Lifecycle.Event.ON_STOP -> playerViewModel.pause()
원래 ON_STOP 에서 releasePlayer()를 호출했었는데, 이것저것바꾸다가 남아있게 된것같습니다! 좀 더 꼼꼼하게 살펴볼게요

2024-11-24 05:53 UTC, miller198 commented on gradle/libs.versions.toml
> +androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
Icon 이미지 벡터 지정할때 Icons에서 훨씬 많은 아이콘들이 나와요

2024-11-24 06:02 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/pick/musicplayer/PlayerViewModel.kt
> +private val INITIAL_PLAYER_STATE = PlayerState(isReady = false)
Player UI 상태를 명시적인 이름으로 편리하게 쓸 생각으로 만들었습니다.
sealed로 ui state 사용할때는 상황별로 사용될 state들을 sealed안에 정의할 수 가 있는데 PlayerState가 sealed가 아니라 데이터 클래스이다보니 그럴수 없었습니다. 그래서 INITIAL, READY, PLAYING 이렇게 명시적인 상태를 미리 만들어두려고 했었는데 현재는 INITIAL만 만들고 나머지는 copy로 기존 PlayerState 값 복사해서 사용하고 있습니다.

사실 데이터 클래스를 그렇게 사용할거면 sealed로 만드는게 나은것같아서 만들어서 사용해봤는데 일시정지,재생, 타임라인 seek 등 매 이벤트마다 PlayerState를 새로 만들어서 사용하다보니 UI 업데이트 속도가 너무 느리더라구요. 터치 이후 약간의 딜레이가 자꾸 발생해서 지금같이 바꾸었습니다.

2024-11-24 06:03 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/MapScreen.kt
> +        }
오오 처음 보는데 LifecycleEventEffect는 라이프사이클 이벤트 한개에 대해 동작을 정의할 수 있네요
옵저버 제거는 추가하겠습니다

2024-11-24 06:27 UTC, miller198 commented
@meanjoo 

노래가 재생 중인 상태에서 configuration change가 일어나면 노래 재생이 취소되는데 의도한 걸까요?
-> 어디 화면 말씀하시는지 모르겠지만 지금 플레이어는 configuration change 대응이 어려워서 안되어있습니다

배너를 클릭할 때마다 노래가 재생/중지되는 것 같은데 어떨 때는 계속 노래가 바뀌고 어떨 때는 이전에 듣던 노래가 중지된 이후부터 다시 재생되는 것 같은데 제 기분 탓인가요??
-> 일단 노래바뀌는건 ExoPlayer의 셔플 기능에 맡겨두고 있어서 제가 마음대로 조정이 안됩니다. 원래 pick 리스트에서 random() 으로 골라서 재생했는데 자꾸 똑같은게 또 들리기도 하고,ExoPlyaer에 셔플이 있길래 사용해봤습니다.
이전에 듣던게 일시정지 되는 경우는 셔플재생이 현재 플레이리스트의 모든 노래를 한번만 재생하는건데 마지막 노래에 다다랐을경우 다음 노래가 없어서 그렇게 되더라구요. 이건 그냥 ExoPlayer의 셔플을 사용하기보단 랜덤함수로 노래 고르는 상태로 되돌리는게 나을것같네요 반영해서 다시 올리겠습니다.

배너를 누르면 30초 미리듣기 음원이 랜덤으로 하나 재생되는데 30초 이후에는 다른 노래가 나오지 않고 배너가 아래처럼 된 상태로 그대로 유지되는 것 같습니다. 이 상태에서 배너를 누르면 이모지가 바뀌지도 않고 노래가 나오지도 않더라구요? 30초가 지나고 다른 노래가 다시 재생되는 게 아니라면 헤드셋 모양의 배너로 다시 바꿔주는 게 어떨까요 아니면 30초 재생이 끝나면 다른 노래를 랜덤으로 계속 재생해주는 것도 좋을 것 같아요!
-> 지금 셔플기능 사용하는 상태에선 곡 하나 끝나고 다음 노래 바로 재생되요 아마 현재 노래가 플레이리스트에서 마지막 노래라면 그런 일이 발생하는것같은데 이것도 ExoPlayer 셔플 사용 안하면 고칠 수 있을것같습니다 

배너를 한 번 클릭할 때마다 리컴포지션이 두 번씩 일어나고 있는 것 같아요. (영상 전체화면으로 보시면 보일 거예요) 근데 이거 보니 배너 누를 때마다 NaverMap도 리컴포지션 두 번씩 일어나네요
-> 무슨 문제인지는 모르겠는데 영상이 1초 이후로 재생이 안되네요 확인해보겠습니다

2024-11-24 06:49 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +private const val INITIAL_CAMERA_ZOOM = 16.0
이것 저것 바꾸다가 다시 고치는거 깜빡하고 넣어버렸습니다 (ㅠ.ㅠ)

2024-11-24 09:18 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/pick/musicplayer/PlayerViewModel.kt
> +private val INITIAL_PLAYER_STATE = PlayerState(isReady = false)
아하 [UI State production](https://developer.android.com/topic/architecture/ui-layer/state-production?hl=en)을 보면 여기서도 data class로 ui state를 쓰고 있는데 data class의 정의를 기본 상태로 두고 나머지 변경에서 copy로 복사해서 사용하는 것 같더라구요. 고쳤으면 좋겠다라기보단 다른 상태들은 이름으로 관리 안 하고 INIT만 따로 빼둔 이유가 궁금해서 여쭤본 거였습니다!

그리고 configuration change 발생 시 노래 재생 취소는 지도 화면에서 배너 누르고 나오는 노래 재생을 말하는 거였습니다. 그쵸 노래 재생 취소되는 건 차차 해결해나가며 되죠! 그런데 저거 보고 상세 화면에서도 configuration change를 시켜봤는데 여기는 재생 취소보다 다른 문제가 있는 것 같아요

https://github.com/user-attachments/assets/f24d4b4d-5119-42aa-a722-807cb8b8049b

처음 재생할 때는 문제가 없는데 configuration change가 일어나면 재생바쪽이 문제가 있어보여요
> 괜히 계속 문제만 찾아오는 것 같아서 죄송하네요..😢

2024-11-24 16:22 UTC, yuni-ju requested changes
특정 노래가 가끔 심하게 끊기는 경우가 있는데 혹시 제 기기에서만 그럴까요?
previeUrl로 확인했는데 음원은 정상인 것 같더라구요 
앞선 코멘트에 언급이 없어서 확인된 문제인지 궁금해서 남깁니다! 

랜덤으로 같은 노래가 계속 나오는 것은 db확인해보니 진짜 같은노래가 한 자리에 많이 등록되어있어서 그런 것 같기도 하네요 ㅎㅎ

2024-11-24 16:22 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +                playerViewModel = hiltViewModel<PlayerViewModel>(),
`playerViewModel = hiltViewModel<PlayerViewModel>()` 요걸 전달하는 대신에
아래와 같이 MapScreen에서 hiltViewModel()을 써도 될 것 같습니다!

```kotlin
@Composable
fun MapScreen(
    mapViewModel: MapViewModel,
    onFavoriteClick: () -> Unit,
    onCenterClick: () -> Unit,
    onSettingClick: () -> Unit,
    onInfoWindowClick: (String) -> Unit,
    playerViewModel: PlayerViewModel = hiltViewModel()
)
```

DetailPickScreen도 동일한 방식으로 바꿀 수 있을 것 같습니다

2024-11-24 16:22 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
컴포저블 함수 분리해주신 것 너무 좋습니다!

2024-11-25 07:44 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/main/MainNavGraph.kt
> +                playerViewModel = hiltViewModel<PlayerViewModel>(),
노래가 처음에 지지직 거리는건 저도 원인을 잘 모르겠습니다

2024-11-25 08:36 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/pick/musicplayer/PlayerViewModel.kt
> +private val INITIAL_PLAYER_STATE = PlayerState(isReady = false)
메인화면이랑 디테일 모두 config change 해결했는데 확인부탁드려요

2024-11-25 09:00 UTC, miller198 commented
지금 올라와 있는 파일 기준 PlayerViewModel의 stop() 함수는 안쓰이고 있지만 일단 무시해주세요!

2024-11-25 12:26 UTC, meanjoo requested changes
정말 고생하셨습니다!!!👏👍👍👍
제 까다로운 의견 많이 들어주셔서 감사합니다..ㅎ 마지막으로 제가 코드에 코멘트 달아둔 부분만 확인해주세요 컴포넌트도 분리해둔 거 봤는데 좋습니다!

2024-11-25 12:26 UTC, meanjoo commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"
이걸 추가함으로써 MapScreen에서 노래 재생의 configuration change를 대응하고 있는 것처럼 보이는데 맞을까요??
제가 하나 고민되는 건 저희는 지금 MainActivity 하나에서 Screen을 다르게 보여주고 있기에 모든 Screen에서 이 속성이 적용될 것처럼 보입니다. 그럼 모든 스크린이 화면 회전 시 다시 생성되지 않을 텐데 저는 MapScreen에서 세로일 때와 가로일 때 보여지는 게 달라지도록 하려고 합니다. 이걸 처리할 수 있는 방법이 있나요?

추가로 지금처럼 orientation 쓰려면 screenSize뿐만 아니라 screenLayout도 정의해줘야 한다고 합니다. [링크](https://developer.android.com/guide/topics/manifest/activity-element?hl=en)
![image](https://github.com/user-attachments/assets/3a79c6ed-8c2e-4481-a7f1-d11154bf942a)

+) 상세화면에서의 configuration changes는 대응해두셔서 상세화면에서는 노래를 재생한 상태로 화면회전이나 다크모드로 바꿔도 재생이 이어서 잘 되더라구요
만약 MapScreen에서 configuration change가 일어났을 때 노래를 이어 재생하는 방법이 이 문장을 추가하는 것밖에 없다면 그냥 이 문장을 없애고 MapScreen에서 노래를 재생한 상태로 화면 회전이나 다크모드로 변경하면 노래 멈추는 걸로 하거나 다른 방법으로 대응하는 건 어떨까욥..?

[공식문서에 best practice](https://developer.android.com/guide/topics/resources/runtime-changes?hl=en#configuration-changes)로 configuration change를 피하지 말라는 말도 있고, 개인적으로도 이렇게 화면 회전 시 재생성 자체를 막아버리는 건 별로 좋지 않다고 생각합니당..
![image5](https://github.com/user-attachments/assets/5af13df9-d2a3-45bb-ac9f-cdf490b3ea38)

그리고 이렇게 configuration change 발생 시 재생성을 막아버리면 화면 회전에는 재생성되지 않는다 해도 다크모드 변경 때는 재생성됩니다..! (-> MapScreen에서 배너 눌러서 노래 재생한 상태로 다크모드로 변경하면 노래 멈춥니다 ㅎ..ㅎ)

2024-11-25 12:26 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/pick/components/music/PlayProgressIndicator.kt
> +        )
혹시 이건 뭘까요??

2024-11-25 13:05 UTC, miller198 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"
네 지도화면에선 그냥 멈추게 해야될것같아요 이거 말곤 방법이 없더라구요

2024-11-25 13:06 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/pick/components/music/PlayProgressIndicator.kt
> +        )
아앗 빼겠습니다

2024-11-25 13:22 UTC, miller198 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"
무식한 방법이긴한데 지도화면에서 다음화면 넘어갈때 무조건 pause()하는걸로 바꿨습니다

2024-11-25 14:45 UTC, yuni-ju approved these changes

2024-11-25 14:52 UTC, meanjoo approved these changes

2024-11-25 15:28 UTC, merged