[feature] 마커 클러스터링
boostcampwm-2024/and06-musicroad pull request #120
Opened 2024-11-26 15:12 UTC by meanjoo

## #️⃣연관된 이슈

> - resolved: #34 

## 📝작업 내용 및 코드

- 마커 클러스터링이 되도록 했습니다.
- 클러스터 마커를 클릭하면 ModalBottomSheet로 클러스터 마커 안에 어떤 픽들이 있는지 정보가 나오도록 구성했습니다.

https://github.com/user-attachments/assets/80e9da83-cc50-4ba2-86a1-cbd84dac9671

### 클러스터링
[네이버 지도 - 마커 클러스터링](https://navermaps.github.io/android-map-sdk/guide-ko/5-8.html)에 의하면 클러스터링은 Clusterer 객체가 수행한다고 하기에 Clusterer 객체를 만들었습니다. Clusterer 객체는 직접 생성할 수 없고 `Clusterer.Builder`나 `Clusterer.ComplexBuilder` 빌더 클래스를 사용하여 생성할 수 있는데, 그 중에서 `Clusterer.ComplexBuilder` 빌더 클래스를 사용하여 생성했습니다. 기본적인 클러스터링만 하려면 `Clusterer.Builder` 사용을 권장하지만 기본적인 클러스터링 동작으로는 제가 원하는 바를 수행할 수 없었습니다. 저는 클러스터 마커를 눌렀을 때 해당 클러스터 마커 안에 어떤 픽들이 있는지 리스트로 정보를 알려주고 싶었습니다.
클러스터 마커 정보가 포함되어 있는 `ClusterMarkerInfo`에는 클러스터의 크기, 노출되는 최소/최대 줌 레벨, 태그 등 클러스터 마커의 정보가 포함되어 있는데, 기본 `Clusterer.Builder`를 사용하여 생성한 클러스터 객체에서는 클러스터 마커의 태그를 지정할 수 없습니다.  `Clusterer.ComplexBuilder`로 생성하면 `tagMergeStrategy()`를 호출하여 자식 노드들의 태그를 병합해서 클러스터 노드의 태그로 삼는 태그 병합 전략을 지정할 수 있습니다. 태그 병합 전략을 지정하기 위해 `Clusterer.ComplexBuilder`로 클러스터 객체를 만들었습니다.
태그 병합 전략을 사용해서 클러스터 노드의 태그를 자식 단말 노드의 픽 id를 ,로 이어붙인 것으로 설정되도록 했습니다.
```kotlin
.tagMergeStrategy { cluster ->
    cluster.children.map { it.tag }.joinToString(",")
}
```

클러스터 마커를 클릭하면 태그를 ,를 기준으로 분할한 픽 id 리스트를 현재 마커 상태의 clusterPickList로 갖게 합니다. 현재 마커 상태는 MapScreen에서 관찰하고 있습니다. 단말 마커를 클릭하면 마커 상태의 curPickId가 null이 아니고, clusterPickList가 null이고, 클러스터 마커를 클릭하면 마커 상태의 curPickId가 null, clusterPickList가 null이 아닙니다. 클러스터 마커를 클릭하면 BottomSheet가 보여지도록 합니다.
```kotlin
clickedMarkerState.prevClickedMarker?.let {
    if (clickedMarkerState.curPickId != null) { // 단말 마커 클릭 시
        showBottomSheet = false
        mapViewModel.picks[clickedMarkerState.curPickId]?.let { pick ->
            /* ... */
        }
    } else { // 클러스터 마커 클릭 시
        showBottomSheet = true
    }
}
```

### 클러스터 마커
네이버 지도 API에서 제공하는 기본 클러스터 마커를 이용했을 때 클러스터링이 반복하면 가끔씩 단말 마커든 클러스터 마커든 크기가 찌그러지는 현상이 있었습니다. 클러스터 마커는 제공되는 걸 쓰고 단말 마커는 커스텀 뷰를 사용하여 두 마커의 크기가 달라서 그런 게 아닐까 추측 중입니다. (마커 재사용 때문?) 따라서 클러스터 마커 아이콘도 단말 마커처럼 커스텀 뷰로 간단하게 구현하기로 했다. 추측한 이유 때문에 클러스터 마커와 단말 마커의 크기를 같게 만들었습니다.

> 이후 테스트에서 마커 크기가 달라서 발생하는 문제라고 거의 확신했습니다. 단말 마커와 클러스터 마커의 커스텀 뷰 크기를 다르게 설정하면 아래처럼 가끔 마커의 크기가 원하는대로 나오지 않는 문제가 있었습니다. (클러스터 마커는 타원이 아니라 원으로 정의했었습니다.) 따라서 커스텀 뷰 자체의 크기는 둘을 동일하게 하고 그 안에서 onDraw()를 조정했습니다.
> <img src="https://github.com/user-attachments/assets/46da4164-cc9a-4e2b-8715-4baf079dda98" width="300">

클러스터 마커는 클러스터링된 개수에 따라 색상 및 크기(미세하게)가 다릅니다. 네이버 지도 API에서 기본적으로 제공하는 클러스터 마커도 밀도에 따라 다른 아이콘을 표시하는 것을 보고 적용하면 좋겠다고 생각했습니다. LOW, MEDIUM, HIGH 기준은 기본 클러스터 마커의 내부를 보고 이와 똑같이 했습니다.

![image (6)](https://github.com/user-attachments/assets/ba4a3224-b49e-426c-a6d1-0c2400d1e61b)

10개 미만일 때는 LOW, 100개 미만일 때는 MEDIUM, 100개 이상일 때는 HIGH입니다. 아래와 같은 DensityType을 만들어서 커스텀 뷰에서 이 값에 따라 마커 아이콘이 뷰가 되도록 했습니다. 색상은 여기()에서 뽑힌 색상을 참고했고 이 중에서 LOW는 80, MEDIUM은 50, HIGH는 20로 설정했습니다.
```kotlin
enum class DensityType(val offset: Int, val color: Int) {
    LOW(4, Primary80.toArgb()),
    MEDIUM(2, Primary50.toArgb()),
    HIGH(0, Primary20.toArgb())
}
```
<img src="https://github.com/user-attachments/assets/284c3a94-1c28-488e-ad03-33312704fb1e" width="300">

### 클러스터 마커 클릭 시 동작
클러스터 마커를 누르면 showBottomSheet가 true가 되고 이때 ModalBottomSheet가 보여지며 클러스터 마커 안에 어떤 픽들이 포함되어 있는지 목록으로 보여지도록 했습니다.

## 💬리뷰 요구사항
- 마커 상태가 아래처럼 되어 있습니다. 마커 상태를 관리하는 게 저는 이게 최선이라 생각했는데 정말 이게 최선인지 잘 모르겠습니다.. 세 개가 다함께 변하고 한 번 필요할 때 다같이 필요해서 묶긴 했습니다.
  ```kotlin
  data class MarkerState(
      val prevClickedMarker: Marker? = null, // 이전에 클릭한 마커(클러스터 마커 & 단말 마커)
      val clusterPickList: List<Pick>? = null, // 클러스터 마커의 픽 정보
      val curPickId: String? = null // 현재 선택한 마커의 pick id
  )
  ```
  클릭된 마커가 단말 마커면 clusterPickList == null, curPickId != null, 클러스터 마커면 clusterPickList != null, curPickId == null입니다.

- 클러스터링이 되는 걸 보다보면 네이버 지도에서 제공하는 기본 단말 마커가 보이는 현상이 있습니다. 

  https://github.com/user-attachments/assets/456a9357-4488-4af7-b7d0-868f5796f65e

  ![image](https://github.com/user-attachments/assets/26f7d168-d2b0-46d3-bbb7-936bc15f713e)

  여기서 super를 호출하는 것 때문에 그런가 하고 super 호출을 지우고 super에서 지정해주던 것을 직접 지정해도 여전히 그렇더라구요.. 왜 그런지 아직 잘 모르겠습니다..

2024-11-27 08:17 UTC, yuni-ju requested changes
우선 코드를 확인하기 전 실행해보았을 때 클러스터링이 자연스럽게 잘 동작함을 확인했습니다 !! 👍 

![list-click](https://github.com/user-attachments/assets/32c36f21-3647-4b02-912a-4a6885a1db27)

그런데 클러스터 바텀시트의 리스트를 클릭해서 픽 화면으로 이동할 때 화면이 겹쳐지다가 사라지는 것이 조금 어색해보였습니다. 화면 전환 시 바텀시트가 겹쳐지지 않고 바로 사라지게 하는 것이 어떤지 의견 제시해봅니다!

2024-11-27 08:50 UTC, meanjoo commented
@yuni-ju 
그렇네요 제가 우와~ 넘어간다!만 하고 끝내버려서 신경쓰지 못했던 부분인 것 같네요 ㅋㅋㅋ

https://github.com/user-attachments/assets/6d53c630-6b22-415e-9ff4-158d4a12b435

이런 식으로 되면 괜찮을까요?

2024-11-27 10:05 UTC, yuni-ju requested changes
복잡한 작업 하시느라 정말 고생 많으셨습니다! 
설명과 주석을 잘 달아주셔서 코드만 보고도 클러스터링 방식이 이해가 되었습니다. 감사합니다!

2024-11-27 10:05 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/common/Image.kt
자주 사용하는 컴포넌트 따로 분리해주신 것 좋습니다! 잘 사용하겠습니다 : ) 

placeholder이외에 error상황일 때 표시할 이미지도 지정해두는 것이 어떨까요?
placeholder와 동일하게 ColorPainter(Gray) 사용해도 좋을 것 같습니다.

2024-11-27 10:05 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +            }
`val pickList = clusterTag?.split(",")?.mapNotNull { id -> picks[id] }`

이렇게하면 변수를 하나 줄일 수 있을 것 같습니다. 

`Log.d("test", "pickList: $pickList")`
그리고 test목적의 로그였다면  실수로 지워지지 않은 것 같습니다!

2024-11-27 10:05 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +                        if (info.tag.toString().contains(curPickId)) {
pickId를 이어붙여서 tag 클러스터 노드의 태그로 사용하는 것 확인했습니다! 

저희 firestore에서 생성되는 pickId의 길이가 항상 일정한가요?? 
혹시나 contains로 다른 픽이 선택되는 경우가 있으려나 생각하다가 궁금해졌습니닷!

2024-11-27 10:05 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
> +            .padding(WindowInsets.statusBars.asPaddingValues()),
![navbar](https://github.com/user-attachments/assets/5e4b794c-46a2-42c6-81f8-41e485e34e4d)

지도화면과 달리 클러스터 바텀시트가 기기의 내비게이션바와 겹쳐지고 있습니닷..!

2024-11-27 10:05 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/ui/theme/Color.kt
> +val Primary20 = Color(87, 29, 30)
컬러를 위아래 방식과 통일하면 좋을 것 같습니다!

2024-11-27 13:03 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/common/Image.kt
> +fun AlbumImage(
커스텀 컴포저블 만들때 modifier를 보통 받게 하지 않나요? 
```kotlin
@Composable
fun AlbumImage(
    modifier: Modifier = Modifier,
    imageUrl: String?,
) {
    AsyncImage(
        model = ImageRequest.Builder(LocalContext.current)
            .data(imageUrl)
            .crossfade(true)
            .build(),
        contentDescription = stringResource(R.string.map_album_image_description),
        modifier = modifier,
        placeholder = ColorPainter(Gray),
        contentScale = ContentScale.Crop,
    )
}

```
이렇게 만들어두고

```kotlin
AlbumImage(
    imageUrl = song.getImageUrlWithSize(RequestImageSize),
    modifier = Modifier
        .size(ImageSize)
        .clip(RoundedCornerShape(16.dp)),
)
```

사용하는 코드에선 이렇게 사용하는게 커스텀 컴포저블 사용하는 법 같습니다.
저도 이렇게 안만든게 많아서 잘 모르겠네요 😅 리뷰를 빙자한 질문입니다

2024-11-27 13:03 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/common/Image.kt
> +fun AlbumImage(
파일명도 Image보단 AlbumImage로 맞추어서 바꾸는게 좋아보입니다

2024-11-27 13:08 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
> +            .padding(WindowInsets.statusBars.asPaddingValues()),
흠 그러네요 스와이프 제스처 내비게이션 바를 계속 써서 몰랐는데 반만 열린 바텀시트일 때 내비게이션 바 뒤에 그려지네요
전체가 열린 건 괜찮은데 반만 열렸을 때 왜 저러는지 모르겠네요..ㅠ 인터넷에 찾아보니 저런 문제가 있는 사례도 있고 해결책도 적어둔 블로그들이 있긴 한데 이것저것 따라해고 시도해봐도 여전하네요,, 일단 두고 조금만 더 알아보겠습니다..!

2024-11-27 13:12 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/common/Image.kt
> +fun AlbumImage(
아하 별 생각없이 앨범 이미지의 AsyncImage modifier가 크기 외에는 다 똑같길래 modifier 대신 이미지 크기랑 둥근 정도를 받게 했는데, modifier를 받는 게 더 나을 것 같네요
파일명을 Image로 한 이유는 공통으로 쓰이는 이미지 중에 앨범 이미지 말고 다른 것도 있으면 저 파일에 함께 넣으려고 한 거였는데 생각해보니 딱히 그런 이미지가 더 있는지 모르겠네요 ㅋㅋㅋ
AlbumImage() 매개변수에 modifier를 넣고 파일명도 AlbumImage로 변경하겠습니다

2024-11-27 13:18 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/common/Image.kt
까먹고 있던 error가 기억났네요! 반영하겠습니당

2024-11-27 13:29 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/MapViewModel.kt
> +            }
엇.. 저 로그는 분명히 지웠던 것 같은데 언제 다시 살아난 거죠.. 지우겠습니당
변수 하나 줄이는 것도 좋네요!

2024-11-27 13:32 UTC, miller198 reviewed
```kotlin
internal fun <T : ClusteringKey> buildClusterer(
    context: Context,
    mapViewModel: MapViewModel,
): Clusterer<T> {
    return Clusterer.ComplexBuilder<T>()
        .thresholdStrategy { zoom ->
            when {
                zoom >= 16 -> 10.0
                zoom >= 13 -> 20.0
                zoom >= 11 -> 40.0
                else -> 70.0
            }
        }
        .tagMergeStrategy { cluster ->
            cluster.children.map { it.tag }.joinToString(",")
        }
        .markerManager(object : DefaultMarkerManager() {
            override fun createMarker(): Marker {
                val marker = Marker()
                with(marker) {
                    icon = OverlayImage.fromView(View(context))
                    setCaptionAligns(Align.Center)
                    captionHaloColor = android.graphics.Color.TRANSPARENT
                }
                return marker
            }
        })
        .clusterMarkerUpdater(object : DefaultClusterMarkerUpdater() {
            override fun updateClusterMarker(info: ClusterMarkerInfo, marker: Marker) {
                // 클릭된 마커가 클러스터 마커 안에 포함되면 클릭된 마커 해제
                mapViewModel.clickedMarkerState.value.curPickId?.let { curPickId ->
                    if (info.tag.toString().contains(curPickId)) {
                        mapViewModel.resetClickedMarkerState(context)
                    }
                }
                val densityType = when {
                    info.size < 10 -> DensityType.LOW
                    info.size < 100 -> DensityType.MEDIUM
                    else -> DensityType.HIGH
                }
                val captionColor = when {
                    densityType == DensityType.LOW -> Black
                    else -> White
                }
                val clusterMarkerIconView = ClusterMarkerIconView(context, densityType)
                marker.icon = OverlayImage.fromView(clusterMarkerIconView)
                marker.anchor = PointF(0.5F, 0.5F)
                marker.captionText = info.size.toString()
                marker.captionColor = captionColor.toArgb()
                marker.onClickListener = Overlay.OnClickListener {
                    marker.map?.let { map ->
                        setCameraToMarker(
                            map = map,
                            clickedMarkerPosition = marker.position
                        )
                        mapViewModel.setClickedMarkerState(
                            context = context,
                            marker = marker,
                            clusterTag = info.tag.toString()
                        )
                    }
                    true
                }
                // 클러스터 마커를 클릭한 채로 configuration change 시 크기 유지
                if (info.tag.toString()
                    == mapViewModel.clickedMarkerState.value.clusterPickList?.joinToString(",") { it.id }
                ) {
                    mapViewModel.setClickedMarker(context, marker)
                }
            }
        })
        .leafMarkerUpdater(object : DefaultLeafMarkerUpdater() {
            override fun updateLeafMarker(info: LeafMarkerInfo, marker: Marker) {
                marker.anchor = Marker.DEFAULT_ANCHOR
                marker.captionText = ""

                val pick = (info.key as MarkerKey).pick
                val leafMarkerIconView = LeafMarkerIconView(context).apply {
                    val color = if (pick.createdBy.userId == mapViewModel.getUserId()) Blue else Primary
                    setPaintColor(color.toArgb())
                }
                leafMarkerIconView.setLeafMarkerIcon(pick) {
                    marker.icon = OverlayImage.fromView(leafMarkerIconView)
                    marker.setOnClickListener {
                        marker.map?.let { map ->
                            setCameraToMarker(
                                map = map,
                                clickedMarkerPosition = marker.position
                            )
                            mapViewModel.setClickedMarkerState(
                                context = context,
                                marker = marker,
                                pickId = pick.id
                            )
                        }
                        true
                    }
                    // 단말 마커를 클릭한 채로 configuration change 시 크기 유지
                    if (pick.id == mapViewModel.clickedMarkerState.value.curPickId) {
                        mapViewModel.setClickedMarker(context, marker)
                    }
                }
            }
        })
        .build()
}

```

map - marker 패키지 안에 이거 넣고

NaverMap에선
```kotlin
DisposableEffect(Unit) {
        clusterer = buildClusterer(context, mapViewModel)
        onDispose {
            clusterer?.clear()
        }
    }
```

이렇게만 사용하는게 좋을것같네요

NaverMap 에서 저 부분 코드가 너무 길어서 파일 분리해봤습니다.
NaverMap 의 setCameraToMarker() 함수 internal로 바꿔야됩니당

2024-11-27 13:32 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
> +    onDismissRequest: () -> Unit,
여기도 똑같이 modifier를 호출하는쪽에서 받고 ModalBottomSheet에 적용하는게 좋아보입니다

2024-11-27 13:38 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +                    }
전 보통 코드가 이렇게 되면
```kotlin
with(marker) { 
    icon = OverlayImage.fromView(clusterMarkerIconView)
    anchor = PointF(0.5F, 0.5F)
    captionText = info.size.toString()
    this.captionColor = captionColor.toArgb()
    onClickListener = Overlay.OnClickListener {
        marker.map?.let { map ->
            setCameraToMarker(
                map = map,
                clickedMarkerPosition = marker.position
            )
            mapViewModel.setClickedMarkerState(
                context = context,
                marker = marker,
                clusterTag = info.tag.toString()
            )
        }
        true
    }
  }
```

이런식으로 씁니다. 성능이나 가독성 효과는 없구요. 그냥 귀찮음을 줄여줍니다

2024-11-27 13:43 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/NaverMap.kt
> +                        if (info.tag.toString().contains(curPickId)) {
저희는 현재 pick의 id를 firestore에서 자동으로 만들어주는 picks의 문서 id로 사용하고 있습니다.
제가 문서에서 못 찾는 건지는 모르겠지만..? 분산형 알고리즘을 사용해서 자동으로 문서 ID를 할당한다고만 하지 몇 글잔지 그런 내용은 안 보이네욥,,
![image](https://github.com/user-attachments/assets/15a27458-c63e-4ddf-a6f9-d29f165228a5)
[출처](https://firebase.google.com/docs/firestore/manage-data/add-data?hl=ko)
![image](https://github.com/user-attachments/assets/c3697cab-30e6-4140-8484-de3b3f76cdd9)
[출처](https://firebase.google.com/docs/firestore/best-practices?hl=ko)

저희 firestore에 추가된 picks의 문서 id를 보면 20글자로 길이가 전부 일정한데, 그럼 일정하지 않을까요,,ㅎㅎ,,
![image](https://github.com/user-attachments/assets/3c20f0cd-bb3a-4856-a96e-e8af8d217e77)

2024-11-28 01:17 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
> +            .padding(WindowInsets.statusBars.asPaddingValues()),
ModalBottomSheet가 반만 열렸을 때 아래를 어떻게 띄우는지 모르겠네욥,,, 이런 문제가 있다는 블로그들을 보고 해도 적용이 안 되더라구요ㅠㅠ..

[공식문서](https://developer.android.com/develop/ui/compose/components/bottom-sheets-partial?hl=en)에서도 ModalBottomSheet의 modifier는 시트가 완전히 확장되었을 때의 modifier라고 해서 ModalBottomSheet의 modifier에는 뭘 적용해도 안 되더라구요
![image](https://github.com/user-attachments/assets/f730f7e9-8b17-463e-b793-57520688c10c)

그래서 결론은 밖이든 안이든 어디서 패딩을 줘도 적용이 안 돼서 반만 열렸을 때는 패딩 적용을 어떻게 하는지 모르겠습니다,,, ~(이래서 ModalBottomSheet가 실험용인 걸까요 ㅎ)~ 완전히 펼쳤을 때는 내비게이션 바 뒤에 가려지지 않아서 일단은 이대로.... 가는 게 어떠한지 조심스레 여쭤봅니다..

2024-11-28 01:44 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/map/components/ClusterBottomSheet.kt
> +            .padding(WindowInsets.statusBars.asPaddingValues()),
`ModalBottomSheet` 자체적인 문제인 것 같네요 🥲 좋습니다!

2024-11-28 01:47 UTC, yuni-ju approved these changes

2024-11-28 02:11 UTC, miller198 approved these changes

2024-11-28 02:15 UTC, merged