[feature] 뮤직비디오 오버레이 화면 및 컨트롤러 구현
boostcampwm-2024/and06-musicroad pull request #125
Opened 2024-11-28 15:20 UTC by yuni-ju

## #️⃣연관된 이슈

- resolved: #88 
- resolved: #90 
- resolved: #91 
- resolved: #92 

## 📝작업 내용 및 코드

1. 뮤직비디오에 화면에 노래 정보, 한마디를 보여주기
   - 화질 표시 추가
   - 화면을 탭하면 페이드인, 아웃으로 정보가 나타남 
2. 영상 재생, 멈춤, 리플레이 기능 구현
   - 영상 종료 시 미리 보기 안내 메시지 보여주기
3. videoplayer 패키지 분리
4. 비디오 검색 필터링 조건 변경
5. Configuration change 대응 
   - viewmodel 생성, 현재 재생 정보 저장 
   - 화면 회전 시 비율 조정

### 오버레이 
|**재생 및 멈춤**|**리플레이**|
|---------------|-----------|
|<img width=200 src="https://github.com/user-attachments/assets/430f9331-55ac-4428-96fd-3f05f3b55337">|<img width=200 src="https://github.com/user-attachments/assets/4b243f40-2311-4e51-a953-9c4b1228246d">|

### **화면 회전** 
<img width=200 src="https://github.com/user-attachments/assets/52dcdcb9-3bd9-4085-bc81-bc34a91ae811">

## 💬리뷰 요구사항(선택)

화면을 회전할 때 detail 픽정보 화면이 잠깐 보여지는데 이는 exoPlayer 객체가 재생성되면서 발생하는 현상으로 보입니다. 
혹시 개선 방안을 알고 계신다면 알려주시면 감사하겠습니다

문제 상황 1. 플레이 버튼 영역을 탭하는 경우 이벤트가 적용되지 않습니다.
문제 상황 2. 영상이 오랫동안 멈춰있는 경우 재시작이 안되는 경우가 있습니다.

위 상황은 추가적인 이슈로 해결하겠습니다!

2024-11-28 17:18 UTC, meanjoo reviewed
고생하셨습니다! 👍👍
화면을 회전할 때 detail 픽 정보 화면이 잠깐 보여지는 문제는 저도 주말에 한 번 생각해보겠습니당

2024-11-28 17:18 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/pick/DetailPickScreen.kt
> +    val initialOffset = videoPlayerViewModel.swipeState.collectAsStateWithLifecycle().value
by를 사용하여 `.value` 없이 `val initialOffset by videoPlayerViewModel.swipeState.collectAsStateWithLifecycle()`로 쓰는 게 더 읽기 좋을 것 같아보입니당

2024-11-28 17:18 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
> +}
enum class의 이름을 VideoPlayerState로 바꾸는 건 어떨까요? musicplayer 패키지 안에도 PlayerState라는 게 있어서 뭔가 헷갈릴 수도 있을 것 같아서요!
이렇게 되면 musicplayer 안에 있는 PlayerState도 MusicPlayerState로 바꾸는 게 좋을 것 같은데 이 부분은 승규님이랑도 얘기해봐야 할 것 같네요 ㅎㅎ

2024-11-28 17:18 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
> +    val playerState: SharedFlow<PlayerState> = _playerState
`_swipePlayState`랑 `_playerState`는 val로 선언해도 될 것 같아요
그런데 `_playerState`는 StateFlow인데 `playerState`는 SharedFlow로 사용하시는 이유가 있을까요?

2024-11-28 17:23 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
> +}
Replay 상태는 비디오에만 있고 관리 방식이 조금씩 다른 것 같아서 `VideoPlayerState`로 바꾸겠습니다! 
그리고 musicplayer처럼 따로 파일로 빼는 것이 좋겠네용

2024-11-28 17:23 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/videoplayer/VideoPlayerViewModel.kt
> +    val playerState: SharedFlow<PlayerState> = _playerState
아앗 실수입니다 ㅎㅎ 발견해주셔서 감사해요!!

2024-11-28 19:06 UTC, miller198 requested changes
1. 뮤비말고 음원재생 중에 화면 회전하면 갑자기 뮤비가 나오네요
뮤비 스와이프로 한번이라도 올렸다가 내리면 그런거같아요

2. 지금 ExoPlayer 인스턴스가 PlayerViewModel이랑 VideoPlayerViewModel이랑 서로 다른거 맞죠? 
3. 뮤비 올렸다 내렸다 할때 음원 시각화에 뮤비 오디오가 표시되고 있어요

2024-11-30 06:01 UTC, yuni-ju commented
@miller198 

> 1. 뮤비말고 음원재생 중에 화면 회전하면 갑자기 뮤비가 나오네요

해당 문제 확인했습니다! offset업데이트가 처음 화면이 생성되는 시점에 호출되어 발생했던 문제였습니다. 
우선 onDispose시점에 스와이프 상태를 저장하는 방식으로 수정하겠습니다.
그리고 해당 이슈 종료 후 다른 방식의 화면 전환(navigation 등)을 고려해보겠습니다. 

> 2. 음원 시각화에 뮤비 오디오가 표시되고 있어요

이 부분은 기기의 모든 소리가 들어가고있었던 것 같습니다!

2024-11-30 06:06 UTC, miller198 approved these changes

2024-11-30 06:15 UTC, meanjoo approved these changes

2024-11-30 06:16 UTC, merged