[fix] 다른 화면으로 전환 후 돌아오면 스낵바가 보이지 않는 문제 해결
boostcampwm-2024/and06-musicroad pull request #146
Opened 2024-12-02 14:40 UTC by meanjoo

## #️⃣ 연관된 이슈
- resolved #145 

## 📝 작업 내용 및 코드
- 권한 2번 거부 시 보여지는 스낵바가 다른 화면으로 전환 후 돌아오면 사라지는 문제를 해결했습니다.

  https://github.com/user-attachments/assets/99cdbd0b-51bd-44bd-8ec6-738bc3667dc3

### 해결 방법
기존에는 스낵바를 사용했었는데 스낵바를 보여주는 부분이 `LaunchedEffect(Unit)` 안에 있었습니다. 이 때문이라 스낵바를 사용하지 않고 그냥 UI를 직접 만드는 방법으로 해결했습니다😅

|라이트모드|다크모드|
|:---:|:---:|
|![image (4)](https://github.com/user-attachments/assets/ef8c2d7f-dcba-4727-9394-a6f2a420b256)|![image (5)](https://github.com/user-attachments/assets/d118290b-4bd5-46c4-82ed-245ffc75bd2c)|

2024-12-02 18:00 UTC, miller198 approved these changes
╰(*°▽°*)╯

2024-12-03 05:23 UTC, yuni-ju requested changes
기존 스낵바랑 똑같이 잘 만들어주셨네요 ㅎㅎ 
설정으로 이동했다가 돌아와도 다시 안내 메세지가 보이는 것을 확인했습니다! 👍

2024-12-03 05:23 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/main/PermissionBar.kt
> +                        overflow = TextOverflow.Ellipsis,
`overflow = TextOverflow.Ellipsis` 를 설정해주셨네요! 

그런데 `maxLines` 설정이 따로 없고, `ElevatedCard`가 `.wrapContentHeight()`로 되어있어서 텍스트의 길이에 따라 높이가 커집니다. 이 정보는 글자를 생략할 필요가 없을 것 같아서 overflow속성을 제거해도 될 것 같습니다.

<img width="327" alt="image" src="https://github.com/user-attachments/assets/5f303ff7-2896-46b3-bbf8-900595ca21a4">

2024-12-03 06:15 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/main/PermissionBar.kt
> +                        overflow = TextOverflow.Ellipsis,
아하 그렇네용
그냥 무의식적으로 overflow를 설정한 것 같네요,, 빼도록하겠습니다!

2024-12-03 07:47 UTC, yuni-ju approved these changes

2024-12-03 07:48 UTC, merged