[feature] 내 프로필과 다른 사람 프로필 구현, 닉네임 수정 기능 구현
boostcampwm-2024/and06-musicroad pull request #147
Opened 2024-12-02 15:47 UTC by yuni-ju

## #️⃣연관된 이슈

> - resolved #41
> - resolved #12
> - resolved #31 
> - resolved #64 

## 📝작업 내용 및 코드

### 1. 프로필에 현재 유저 닉네임 보여주기 
<img width="250" alt="image" src="https://github.com/user-attachments/assets/c1333e97-bf3e-442d-9954-20f43c9cd18f">

### 2. 픽 정보에서 다른 사람의 프로필로 이동하는 기능 구현
- 픽 정보의 닉네임 부분에 밑줄을 표시했습니다.
- 다른 사람의 픽 보관함, 등록한 픽을 볼 수 있습니다.
- 내 프로필을 클릭할 때만 설정 메뉴가 보여집니다.

|다른사람 프로필|내 프로필|
|-------------|---------|
|<video width="250" src="https://github.com/user-attachments/assets/8b4fa767-f27d-434a-853b-234e2abc6507"></video>|<video width="250" src="https://github.com/user-attachments/assets/13d9314a-e5b2-4e2c-82f9-1189633b38b4"></video>|

### 3. 알림 설정 화면에 준비 중 텍스트를 보여주기

<img width="250" alt="image" src="https://github.com/user-attachments/assets/e88c13d7-8f33-4b61-8984-38499fea5f0a">

### 4. 닉네임 변경 기능 구현
- 닉네임 변경 전까지 로딩이 보여집니다.
- 변경 후 프로필 화면으로 돌아가고, 이때 닉네임이 업데이트 됩니다.
- 닉네임 검증 로직 (한글,영어,숫자만 가능 / 2글자 이상/ 10글자 이하, 중복 가능) 
- 닉네임 검증 조건에 맞지 않다면 에러 메시지가 뜨며 닉네임을 변경할 수 없습니다. 

https://github.com/user-attachments/assets/1d3276ae-25e9-4410-a587-2e91426e6f2f

2024-12-02 18:42 UTC, meanjoo requested changes
제가 닉네임 한다면 하려고 한 부분들을 다 하셨군요 ㅎㅎ 고생하셨습니다!

1. 닉네임을 변경하고 나면 토스트 메시지가 뜨는데 키보드가 올라간 상태에서 완료하면 화면 중앙에 토스트 메시지가 보이네욥 키보드 내린 상태로 하면 괜찮은데,, 이건 그냥 어쩔 수 없는 거겠죠?

  https://github.com/user-attachments/assets/adc8c561-6cbb-49ca-a398-678ddbdc87ca

2. 닉네임이 변화가 없을 때도 버튼이 활성화되어 있어서 변경이 되는데 의도하신 걸까요? 개인적으로는 닉네임이 변화가 없을 때는 버튼을 비활성화 시켜도 좋을 것 같습니다!

  https://github.com/user-attachments/assets/3588c94c-79bf-44de-8aeb-222cbe1673a0

2024-12-02 18:42 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/common/CreatedByPickText.kt
> +        append(stringResource(R.string.pick_created_by_self_2))
```suggestion
        append(" ${stringResource(R.string.pick_created_by_self_2)}")
```

요렇게 바꿔야 할 것 같습니당 `내가등록한`이 붙어있어요!

![image](https://github.com/user-attachments/assets/5f83f765-8d16-487d-8c5d-8045f6ae310b)

반영하면 이렇게 됩니다

![image](https://github.com/user-attachments/assets/93bb34e1-8ac6-4d82-9693-f130b4158596)

2024-12-02 18:42 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/setting/SettingProfileScreen.kt
> +}
`"^[ㄱ-ㅎ|ㅏ-ㅣ가-힣a-zA-Z0-9]+$"`는 따로 변수로 빼서 사용하는 것도 좋을 것 같아요
```kotlin
Pattern.matches(USERNAME_PATTERN, userName).not()

private const val USERNAME_PATTERN = "^[ㄱ-ㅎ|ㅏ-ㅣ가-힣a-zA-Z0-9]+$"
```

그리고 return when 쓰는 것도 괜찮아보이는데 취향 차이인 것 같네요 ㅎㅎ
```kotlin
return when {
    userName.length < 2 -> context.getString(R.string.setting_profile_nickname_message_length_fail_min)
    userName.length > 10 -> context.getString(R.string.setting_profile_nickname_message_length_fail_max)
    Pattern.matches(USERNAME_PATTERN, userName)
        .not() -> context.getString(R.string.setting_profile_nickname_message_format_fail)

    else -> ""
}
```

2024-12-02 18:44 UTC, meanjoo commented on data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +
닉네임 바꾸면 저희 db 구조 상 picks에서도 변경해야 하지 않나요??
제가 못 찾은 건지 그런 코드가 안 보여서 여쭤봅니다!

2024-12-03 05:21 UTC, miller198 reviewed
민주님이 리뷰를 잘해주셔서 제가 할게 없네용

2024-12-03 05:46 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/common/CreatedByPickText.kt
> +        append(stringResource(R.string.pick_created_by_self_2))
이거 바꾸면 
![image](https://github.com/user-attachments/assets/1947e149-40af-4813-942c-258d10fafb64)

얘도 바뀌겠죠??

2024-12-03 05:47 UTC, yuni-ju commented on app/src/main/java/com/squirtles/musicroad/common/CreatedByPickText.kt
> +        append(stringResource(R.string.pick_created_by_self_2))
네 맞습니다!! 수정하겠습니다

2024-12-03 09:21 UTC, yuni-ju commented on data/src/main/java/com/squirtles/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +
닉네임 변경 시 픽 정보도 업데이트하는 기능 추가했습니다!

2024-12-03 09:47 UTC, miller198 approved these changes

2024-12-03 10:11 UTC, meanjoo commented
@yuni-ju 
새로 반영된 것들과 닉네임 변경 시 픽 정보도 업데이트 하는 거 확인했습니다! 고생하셨습니다 👏👏

그런데 혹시 픽 보관함이랑 등록한 픽에서 지도로 돌아갈 수 있는 버튼을 만드는 건 어떨까요? 이제 픽에서 유저 닉네임을 눌러 안으로 들어갈 수 있는데 계속 백스택에 쌓으면서 가는 거라 만약 유저 정보를 많이 타고 들어가면 뒤로 가기를 눌렀을 때 하나씩 빠져서 다시 지도로 돌아오기가 힘들 것 같다고 생각했습니다.

https://github.com/user-attachments/assets/b3a95981-7be2-4a43-93ad-b99f44adcb6a

제가 상단바에 추가해둔 지도 버튼을 영상에서 누르지는 않았지만 저 버튼을 누르면 백스택을 전부 제거하면서 메인으로 돌아갑니다.
어떤 것 같나욥??!

2024-12-03 11:33 UTC, meanjoo approved these changes

2024-12-03 11:36 UTC, merged