Feature/#10 apple music
boostcampwm-2024/and06-musicroad pull request #93
Opened 2024-11-12 07:38 UTC by miller198

## #️⃣연관된 이슈

> closes #33 
closes #87 
closes #10 
closes #15

## 📝작업 내용 및 코드

* 민주님
  * 검색화면 UI 
  * 지도에서 중앙 버튼 클릭 시 검색화면으로 이동
* Friestore 테스트 데이터들 애플뮤직에 맞게 수정
![image](https://github.com/user-attachments/assets/4246b850-485f-43e0-ba17-7f1b082bf065)
* 애플뮤직 API 요청에 관련된 data , domain 모듈 model 정의
* 애플뮤직 REST API 인터페이스 정의
![image](https://github.com/user-attachments/assets/f066055e-ce74-4a90-b3e3-cd90b28879e9)
* 애플뮤직 DataSource 인터페이스 및 Impl 클래스 구현
* 노래 검색 및 뮤직비디오 검색 유스케이스 추가
* 애플뮤직 Repository 구현
* Search View Model 구현
* 검색 화면에서 검색 결과 받아오는 것 테스트 완료, 뮤직비디오 테스트 X
  * 현재 검색화면에서 텍스트 입력 후 검색 버튼 누르면 데이터는 받아오는 상태입니다
* 검색 텍스트 입력 시에만 검색 버튼이 보이도록 수정
|![image](https://github.com/user-attachments/assets/011face4-ebe6-4344-9426-d6df4fe93ae8)|![image](https://github.com/user-attachments/assets/8ae316fc-47f4-4c7a-8dcf-88d0ca470f3c)|

* UI 조정 - Scaffold의 Topbar 사용, inset 패딩 설정 

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>

에러처리 봐주세요

AppleMusicDataSourceImpl 에서 checkResponse() 함수로 API 요청 후 응답이 에러라면 예외 던지는데
이를 AppleMusicRepositoryImpl에서 받아서 Result.failure(error message)로 처리해서 뷰모델까지 전달합니다.

발생할 수 있는 에러는 400, 401, 500 이 있는데
401,500 은 명확하지만 400의 경우 검색 요청 보낼때 필수 파라미터가 누락 혹은 올바르지 않은 경우, 검색결과가 없는 경우 같이
여러가지 경우가 있어서 얘네들을 명확하게 분류하기 위해 AppleMusicException 예외 클래스를 따로 만들었어요

근데 만들고보니 InvalidParameterException 예외는 쓰이는 경우가 없을것같아서 (파라미터 설정을 저희가 코드로 해놓으니까 유저가 건들일 일이 없음) 그냥 AppleMusicException  클래스를 없애도 될것같은데 의견 부탁드립니다.

2024-11-12 09:31 UTC, yuni-ju reviewed
애플 뮤직 API 설정부터 Firestore 데이터 변경까지 고생하셨습니다 👍

2024-11-12 09:32 UTC, yuni-ju requested changes

2024-11-12 09:32 UTC, yuni-ju commented on data/src/main/java/com/squirtles/data/datasource/remote/applemusic/AppleMusicDataSourceImpl.kt
> +    }
companion object는 코틀린 컨벤션에 따라 클래스의 가장 아래에 있는 것이 좋을 것 같습니다.

2024-11-12 09:33 UTC, yuni-ju reviewed
검색 텍스트 입력을 하지 않더라도 아이콘이 보이는 것은 어떤가요? 
만약 비어있는 값으로 검색이 불가능하게 하고싶다면 클릭만 막아두면되지 않을까 싶습니다.

`AppleMusicException`은 말씀하신대로 처리를 잘 해둔다면 없어도 될 것 같습니다!

2024-11-12 10:19 UTC, meanjoo commented on data/src/main/java/com/squirtles/data/datasource/remote/applemusic/model/Attributes.kt
> +    val previews: List<Preview>
SerialName 어노테이션을 붙일 거면 이름이 같더라도 모두 붙이는 게 가독성 측면에서 낫다는 피드백을 이전에 받은 적이 있습니다.
피드백을 수용한 후에 일부분만 어노테이션이 붙은 것과 어노테이션이 모두 붙은 것을 비교해봤을 때 어노테이션이 모두 붙은 게 제 눈에 더 보기 좋았었는데, @SerialName이 붙지 않은 나머지 변수들에도 어노테이션을 붙이는 건 어떨까요?

2024-11-12 10:32 UTC, meanjoo commented
현재 AppleMusicException 안에 InvalidParameterException, NotFoundException 두 개가 있던데 만약 InvalidParameterException이 필요 없고 NotFoundException으로 400 에러 처리가 다 될 것 같으면 저도 윤겸님과 마찬가지로 AppleMusicException이 없어도 된다고 생각합니다. NotFoundException 외에 몇 가지 구분할 게 생긴다면 있는 것도 좋을 것 같긴 해요
고생하셨습니다!!

@yuni-ju 오 좋은 의견인 것 같습니다! 검색 텍스트 입력 안 했을 때 검색 아이콘이 없는 것보다는 검색 아이콘 색을 회색이나 상호작용 불가능해보이는 색으로 변경하고 클릭이 안 되게 하면 좋을 것 같아요

2024-11-12 12:37 UTC, meanjoo requested changes

2024-11-12 12:37 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +            ) {
topBar 영역 윗쪽에 여백을 조금 주거나 SearchBar 자체에서 윗쪽에 공간을 주는 건 어떨까요?
코드를 받아서 실행한 화면을 캡쳐한 것이 아래 이미지입니다.

<img src="https://github.com/user-attachments/assets/8d61fcc6-894e-41dd-8951-5f0a950c7a64" width="250">

위 이미지만 봤을 때는 문제가 없어보이는데 제 실물 기기로 봤을 때 이렇게 보입니다.

<img src="https://github.com/user-attachments/assets/6369970b-bfed-4e10-8a58-b929bb22c41f" width="350">

카메라 부분과 검색바 윗부분이 바로 맞닿아 있어서 뭔가 조금 떨어졌으면 하는 마음이 있습니다!

2024-11-12 12:37 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/search/SearchViewModel.kt
> +package com.squirtles.musicroad.search2
패키지가 `com.squirtles.musicroad.search`여야 할 것 같습니다.

2024-11-12 12:52 UTC, meanjoo requested changes

2024-11-12 12:52 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +                            contentDescription = "stringResource(R.string.search_music_search_button_description)",
양끝에 큰따옴표가 없어야 됩니다.

이렇게 하면 contentDescription이 strings.xml에 있는 search_music_search_button_description이 되는 것이 아니라 stringResource(R.string.search_music_search_button_description) 자체가 contentDescription이 되지 않을까요?

MusicItem 안의 AsyncImage에도 똑같이 수정해주시면 좋을 것 같습니다.

2024-11-12 13:00 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +            shape = CircleShape,
제가 빼먹은 건데 혹시 여기 사이에 `singleLine = true,` 추가해주실 수 있나요 ㅎㅎ..

2024-11-12 13:06 UTC, yuni-ju requested changes

2024-11-12 13:06 UTC, yuni-ju commented on domain/src/main/java/com/squirtles/domain/model/Song.kt
Song타입을 추가하시면서 기존 Pick 데이터클래스의 노래 정보들을 Song타입으로 대체하면 좋을 것 같습니다.

2024-11-12 13:14 UTC, meanjoo requested changes

2024-11-12 13:14 UTC, meanjoo commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +    val isSearching by searchViewModel.isSearching.collectAsState(false)
`collectAsState()`보다 `collectAsStateWithLifecycle()`를 사용하는 것이 더 좋을 것 같습니다.

2024-11-13 00:45 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +                            contentDescription = "stringResource(R.string.search_music_search_button_description)",
작업하다가 중간에 strings.xml에 저 문자열이 없어서 잠깐 임시로 에러 뜨지 않게 처리해뒀습니다 지금은 있어요
다시 고친다는걸 깜빡했네요 감사합니다

2024-11-13 00:51 UTC, miller198 commented on domain/src/main/java/com/squirtles/domain/model/Song.kt
이건 논의를 해봐야할것같네요

2024-11-13 02:32 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/search/SearchMusicScreen.kt
> +    val isSearching by searchViewModel.isSearching.collectAsState(false)
반영했습니다!

2024-11-13 02:32 UTC, miller198 commented on app/src/main/java/com/squirtles/musicroad/search/SearchViewModel.kt
> +package com.squirtles.musicroad.search2
감사합니다 통합과정에서 실수가 ㅎㅎ

2024-11-13 02:33 UTC, yuni-ju approved these changes

2024-11-13 02:36 UTC, meanjoo approved these changes

2024-11-13 02:37 UTC, merged